In [1]:
from keras.models import load_model
from keras.preprocessing import sequence
import numpy as np
import pandas as pd

Using TensorFlow backend.
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lab606a/.virtualenvs

In [2]:
model = load_model('./saved model/classifier20200226_25')

In [3]:
maxlen = 75

In [4]:
def CNT():
    for i in range (pred.shape[0]):
        for j in range (4):
            if max(pred[i,:]) == pred[i,j]:
                cnt[j] += 1

In [5]:
def DET(traj):
    for i in range(3,maxlen,3):
        test = test_up2[traj,:]
        test = test.reshape(1,test.shape[0])
        #print(test.shape)
        tmp = test[:,:i]
        tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
        #print(tmp)
        pred = model.predict(tmp)
        np.set_printoptions(suppress=True)
        #print(pred)
        print("number of balls =", int(i/3), ", probability =", pred)
        
        if max(pred[0,:]) == pred[:,0]:
            print("top spin")
        elif max(pred[0,:]) == pred[:,1]:
            print("left spin")
        elif max(pred[0,:]) == pred[:,2]:
            print("right spin")
        elif max(pred[0,:]) == pred[:,3]:
            print("back spin")
        

In [6]:
def DET2(test2):
    for j in range(test2.shape[0]):
        print("trajectory", j)
        for i in range(3,maxlen,3):
            test = test2[4,:]
            test = test.reshape(1,test.shape[0])
            tmp = test[:,:i]
            tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
            pred = model.predict(tmp)
            np.set_printoptions(suppress=True)
            #print(pred)
            print("number of balls =", int(i/3), ", probability =", pred)
        
            if max(pred[0,:]) == pred[:,0]:
                print("top spin")
            elif max(pred[0,:]) == pred[:,1]:
                print("left spin")
            elif max(pred[0,:]) == pred[:,2]:
                print("right spin")
            elif max(pred[0,:]) == pred[:,3]:
                print("back spin")
                
        print("--------------------------")
        if max(pred[0,:]) == pred[:,0]:
            cnt2[0] += 1
        elif max(pred[0,:]) == pred[:,1]:
            cnt2[1] += 1
        elif max(pred[0,:]) == pred[:,2]:
            cnt2[2] += 1
        elif max(pred[0,:]) == pred[:,3]:
            cnt2[3] += 1

In [7]:
cnt = np.array([0,0,0,0])

In [8]:
cnt2 = np.array([0,0,0,0])

In [9]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/up_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
test_up2.shape
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
test_up2.shape

(83, 75)

In [10]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred)
CNT()
print(cnt)

[[0.00010242 0.9990049  0.00071628 0.00017641]
 [0.00074703 0.99894387 0.00023151 0.00007762]
 [0.00011079 0.99959606 0.00024794 0.00004526]
 [0.00017603 0.99840397 0.00079855 0.00062143]
 [0.9421514  0.0220214  0.03570072 0.0001265 ]
 [0.00602576 0.06967164 0.92406374 0.00023889]
 [0.01630952 0.16883662 0.814761   0.0000929 ]
 [0.99943453 0.00024379 0.00030923 0.00001241]
 [0.9997458  0.00012278 0.00012654 0.00000495]
 [0.00006814 0.9992287  0.00057907 0.00012412]
 [0.99841046 0.00114269 0.00042897 0.00001779]
 [0.9997334  0.00009086 0.00016959 0.00000616]
 [0.999556   0.00010417 0.00032942 0.00001041]
 [0.9997116  0.00014883 0.00013433 0.00000518]
 [0.0013575  0.99837494 0.00018986 0.00007774]
 [0.9997384  0.00011954 0.00013771 0.00000432]
 [0.99971896 0.00015031 0.00012508 0.00000566]
 [0.99975103 0.00011244 0.00013171 0.00000486]
 [0.9997354  0.0001226  0.00013647 0.00000544]
 [0.99974555 0.00012139 0.00012849 0.00000456]
 [0.99957365 0.0002966  0.00011813 0.00001168]
 [0.99965906 

In [11]:
#cnt2 = np.array([0,0,0,0])
#DET2(test2=test_up2)
#print(cnt2)

In [12]:
#pred.shape

In [13]:
'''
for i in range (pred.shape[0]):
    for j in range (4):
        if max(pred[i,:]) == pred[i,j]:
            cnt[j] += 1
    #print(max(pred[i,:]))
print(cnt)
'''

'\nfor i in range (pred.shape[0]):\n    for j in range (4):\n        if max(pred[i,:]) == pred[i,j]:\n            cnt[j] += 1\n    #print(max(pred[i,:]))\nprint(cnt)\n'

In [14]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/up_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(84, 75)
(84, 75)


In [15]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(84, 4)
[[0.9997402  0.00011455 0.00014067 0.00000461]
 [0.9997502  0.00010921 0.00013609 0.00000451]
 [0.9997451  0.00011167 0.00013847 0.00000473]
 [0.9997516  0.0001143  0.00012937 0.00000471]
 [0.9997248  0.00014222 0.00012661 0.00000641]
 [0.9997484  0.00011048 0.00013664 0.00000453]
 [0.99974376 0.00012199 0.00012854 0.00000563]
 [0.9979292  0.000084   0.00195228 0.00003457]
 [0.99975175 0.00010231 0.00014098 0.000005  ]
 [0.9997428  0.00009573 0.0001559  0.00000562]
 [0.99973184 0.00008792 0.00017432 0.00000585]
 [0.9997365  0.00013382 0.00012396 0.00000572]
 [0.99975115 0.00011362 0.0001303  0.00000491]
 [0.9992545  0.00036871 0.00036413 0.00001269]
 [0.99975115 0.00011498 0.00012889 0.00000493]
 [0.99973744 0.00012673 0.00012977 0.00000604]
 [0.9997311  0.00012453 0.00013822 0.00000607]
 [0.9997391  0.00011618 0.00013883 0.00000586]
 [0.99972636 0.0001225  0.00014442 0.00000664]
 [0.999684   0.0001093  0.00019742 0.00000935]
 [0.08399624 0.00224151 0.9136315  0.00013079]
 [0.0

In [16]:
#cnt2 = np.array([0,0,0,0])
#DET2()
#print(cnt2)

In [17]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/left_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(83, 75)
(83, 75)


In [18]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(83, 4)
[[0.0000802  0.9996092  0.0001028  0.00020789]
 [0.0001113  0.9997764  0.00007628 0.00003593]
 [0.00005723 0.00020612 0.9996505  0.0000862 ]
 [0.00026107 0.9995623  0.00013049 0.00004609]
 [0.99698824 0.0023005  0.00068632 0.00002501]
 [0.00013365 0.9989428  0.00007236 0.00085129]
 [0.00015647 0.99956626 0.00006319 0.00021408]
 [0.00161586 0.8686818  0.08849291 0.04120945]
 [0.00004875 0.99988043 0.00002923 0.00004152]
 [0.01336804 0.98634887 0.00015391 0.00012927]
 [0.00009102 0.99982893 0.00005823 0.0000218 ]
 [0.00011757 0.9996939  0.00007935 0.00010924]
 [0.00026467 0.99951124 0.00007703 0.00014715]
 [0.00005761 0.9998254  0.00003372 0.00008331]
 [0.00004853 0.9998166  0.0000294  0.00010558]
 [0.00026226 0.9995048  0.00010939 0.00012353]
 [0.00008996 0.99981004 0.00005781 0.00004225]
 [0.00010967 0.9997849  0.00005056 0.00005491]
 [0.0000784  0.9998186  0.00006373 0.00003922]
 [0.00013912 0.9996685  0.00012699 0.00006544]
 [0.00012821 0.9997569  0.00008339 0.00003147]
 [0.9

In [19]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/left_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(69, 75)
(69, 75)


In [20]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(69, 4)
[[0.00010783 0.9997688  0.00008349 0.00003982]
 [0.0000955  0.99978906 0.00007244 0.00004304]
 [0.0000735  0.9996848  0.00004697 0.00019469]
 [0.00006699 0.9996792  0.0001442  0.00010958]
 [0.00012046 0.9997708  0.00007973 0.00002891]
 [0.00007815 0.999813   0.00007594 0.00003285]
 [0.00007123 0.9998018  0.00007531 0.00005158]
 [0.00006544 0.9997118  0.00016304 0.00005965]
 [0.00008918 0.999801   0.00007787 0.00003198]
 [0.00007217 0.99981195 0.00007187 0.00004403]
 [0.00006921 0.9998136  0.00006954 0.00004763]
 [0.0000587  0.9993581  0.00044585 0.00013726]
 [0.00006888 0.99976844 0.00011361 0.00004902]
 [0.00007291 0.99980956 0.00007166 0.00004591]
 [0.0000704  0.99981457 0.00007317 0.00004183]
 [0.00006677 0.9996929  0.00017554 0.00006482]
 [0.00007247 0.99979    0.00006218 0.00007534]
 [0.00005699 0.99983954 0.00005199 0.00005148]
 [0.000069   0.9998338  0.0000661  0.00003105]
 [0.00007341 0.99980456 0.00007428 0.00004773]
 [0.00006199 0.9998455  0.00006283 0.00002961]
 [0.0

In [21]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/back_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(71, 75)
(71, 75)


In [22]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(71, 4)
[[0.00000486 0.0000797  0.00034333 0.9995721 ]
 [0.00001147 0.00013798 0.00210915 0.99774134]
 [0.00000413 0.00007898 0.00025952 0.9996574 ]
 [0.00000696 0.0001023  0.00037288 0.9995179 ]
 [0.00002847 0.00208485 0.00003552 0.99785113]
 [0.00007688 0.0328734  0.00010727 0.96694237]
 [0.00023921 0.11770394 0.00010755 0.8819493 ]
 [0.00004532 0.00020104 0.01707843 0.9826752 ]
 [0.00000972 0.00039867 0.00004224 0.99954945]
 [0.00003269 0.01925187 0.0198899  0.9608256 ]
 [0.00021885 0.03613715 0.00003832 0.96360564]
 [0.00000411 0.00004288 0.00008894 0.9998641 ]
 [0.00000955 0.00022774 0.00004391 0.99971884]
 [0.00000723 0.00014779 0.00007201 0.99977297]
 [0.00000559 0.00009629 0.00005968 0.99983835]
 [0.00000853 0.00018159 0.00004052 0.9997694 ]
 [0.00019649 0.01054074 0.00002457 0.98923826]
 [0.00000941 0.0001624  0.00007256 0.99975556]
 [0.00000717 0.00020092 0.00003967 0.9997522 ]
 [0.00000425 0.00004124 0.00012301 0.99983144]
 [0.00000865 0.00004893 0.0001686  0.9997738 ]
 [0.0

In [23]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/back_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(80, 75)
(80, 75)


In [24]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(80, 4)
[[0.00000533 0.00004568 0.00008375 0.9998652 ]
 [0.00000571 0.0000546  0.00006948 0.9998702 ]
 [0.0000081  0.00009589 0.00008916 0.99980694]
 [0.00000517 0.00008433 0.00006875 0.9998417 ]
 [0.00052247 0.00222394 0.633215   0.3640386 ]
 [0.00000769 0.00006088 0.00013282 0.9997987 ]
 [0.00002186 0.00005454 0.00057356 0.99935   ]
 [0.00000694 0.00006537 0.00011079 0.99981683]
 [0.00000929 0.00051186 0.00007801 0.99940085]
 [0.00000648 0.00007839 0.00009981 0.9998154 ]
 [0.00000745 0.0001429  0.00005046 0.9997993 ]
 [0.00000861 0.00004877 0.00022252 0.99972016]
 [0.00000554 0.0000522  0.00006367 0.99987864]
 [0.00000423 0.00010393 0.00031331 0.99957854]
 [0.0000085  0.00004052 0.00015499 0.9997961 ]
 [0.00001088 0.00008794 0.00047159 0.99942964]
 [0.00004    0.00016577 0.00019046 0.9996038 ]
 [0.00000551 0.00004623 0.00007059 0.9998777 ]
 [0.00000562 0.00005311 0.00007011 0.99987113]
 [0.00000619 0.00006076 0.00006911 0.99986386]
 [0.00000751 0.00006038 0.00007269 0.99985933]
 [0.0

In [25]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/right_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
cnt = np.array([0,0,0,0])
CNT()
print(cnt)

(67, 75)
(67, 75)
(67, 4)
[[0.00008754 0.0001384  0.9996661  0.00010795]
 [0.00010548 0.00013141 0.99966955 0.00009355]
 [0.00018869 0.00008263 0.99966955 0.00005911]
 [0.00007988 0.00009054 0.9996245  0.00020513]
 [0.000087   0.00009113 0.99962294 0.00019894]
 [0.00008887 0.00008906 0.9996189  0.00020322]
 [0.00009466 0.000093   0.9996234  0.00018892]
 [0.0000663  0.00014594 0.99969923 0.00008861]
 [0.00005128 0.00015877 0.9996977  0.00009238]
 [0.00008377 0.00010684 0.99963665 0.00017269]
 [0.00009904 0.00018542 0.99938476 0.00033077]
 [0.00007541 0.0000755  0.99942064 0.0004284 ]
 [0.00007696 0.00008323 0.99954045 0.00029948]
 [0.00041848 0.03336848 0.9491278  0.01708517]
 [0.0000981  0.00013358 0.99956924 0.00019907]
 [0.00006232 0.00012868 0.9996965  0.00011251]
 [0.00087016 0.00086336 0.7659919  0.23227459]
 [0.00005792 0.0001331  0.9997316  0.00007737]
 [0.00008791 0.0001152  0.99971896 0.00007795]
 [0.00005892 0.00010652 0.9995421  0.00029247]
 [0.000084   0.00011706 0.9996799 

In [26]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/25/right_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
cnt = np.array([0,0,0,0])
CNT()
print(cnt)

(74, 75)
(74, 75)
(74, 4)
[[0.00007675 0.00016688 0.9996387  0.00011757]
 [0.00009365 0.00012296 0.99966824 0.00011517]
 [0.00010708 0.00010074 0.9995962  0.000196  ]
 [0.00009214 0.00014389 0.9996123  0.0001517 ]
 [0.00017192 0.00077694 0.9913722  0.00767887]
 [0.00010509 0.00010927 0.99960667 0.00017903]
 [0.00010414 0.00018268 0.999468   0.00024526]
 [0.0002124  0.8220807  0.07795939 0.09974758]
 [0.000102   0.00011789 0.9995702  0.00020998]
 [0.0002138  0.00824537 0.9701211  0.0214197 ]
 [0.00019761 0.00008031 0.9996457  0.00007641]
 [0.00010881 0.00011778 0.9996383  0.00013502]
 [0.0001832  0.01074951 0.98133713 0.00773018]
 [0.00008027 0.0001376  0.9996468  0.00013543]
 [0.00008024 0.00014703 0.99963903 0.00013367]
 [0.00009868 0.00012908 0.9996809  0.00009135]
 [0.00008431 0.00014831 0.99968445 0.00008299]
 [0.00010274 0.00013178 0.999602   0.00016352]
 [0.00008532 0.00015749 0.99962664 0.00013053]
 [0.00010943 0.00012253 0.99964774 0.00012021]
 [0.00010482 0.00012516 0.9995315 