In [1]:
from keras.models import load_model
from keras.preprocessing import sequence
import numpy as np
import pandas as pd

Using TensorFlow backend.
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lab606a/.virtualenvs

In [28]:
model = load_model('./saved model/classifier20200226')

In [29]:
maxlen = 45

In [30]:
def CNT():
    for i in range (pred.shape[0]):
        for j in range (4):
            if max(pred[i,:]) == pred[i,j]:
                cnt[j] += 1

In [31]:
def DET(traj):
    for i in range(3,maxlen,3):
        test = test_up2[traj,:]
        test = test.reshape(1,test.shape[0])
        #print(test.shape)
        tmp = test[:,:i]
        tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
        #print(tmp)
        pred = model.predict(tmp)
        np.set_printoptions(suppress=True)
        #print(pred)
        print("number of balls =", int(i/3), ", probability =", pred)
        
        if max(pred[0,:]) == pred[:,0]:
            print("top spin")
        elif max(pred[0,:]) == pred[:,1]:
            print("left spin")
        elif max(pred[0,:]) == pred[:,2]:
            print("right spin")
        elif max(pred[0,:]) == pred[:,3]:
            print("back spin")
        

In [32]:
def DET2(test2):
    for j in range(test2.shape[0]):
        print("trajectory", j)
        for i in range(3,maxlen,3):
            test = test2[4,:]
            test = test.reshape(1,test.shape[0])
            tmp = test[:,:i]
            tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
            pred = model.predict(tmp)
            np.set_printoptions(suppress=True)
            #print(pred)
            print("number of balls =", int(i/3), ", probability =", pred)
        
            if max(pred[0,:]) == pred[:,0]:
                print("top spin")
            elif max(pred[0,:]) == pred[:,1]:
                print("left spin")
            elif max(pred[0,:]) == pred[:,2]:
                print("right spin")
            elif max(pred[0,:]) == pred[:,3]:
                print("back spin")
                
        print("--------------------------")
        if max(pred[0,:]) == pred[:,0]:
            cnt2[0] += 1
        elif max(pred[0,:]) == pred[:,1]:
            cnt2[1] += 1
        elif max(pred[0,:]) == pred[:,2]:
            cnt2[2] += 1
        elif max(pred[0,:]) == pred[:,3]:
            cnt2[3] += 1

In [33]:
cnt = np.array([0,0,0,0])

In [34]:
cnt2 = np.array([0,0,0,0])

In [35]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/up_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
test_up2.shape
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
test_up2.shape

(83, 45)

In [36]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred)
CNT()
print(cnt)

[[0.00007705 0.0025163  0.04006053 0.9573461 ]
 [0.00030804 0.9186559  0.07952423 0.00151178]
 [0.00007505 0.00071464 0.99844474 0.00076559]
 [0.00002877 0.99864334 0.00105726 0.00027062]
 [0.00079785 0.17382142 0.8209421  0.00443863]
 [0.00003998 0.9976102  0.0021622  0.00018768]
 [0.0004436  0.32443252 0.60706866 0.06805523]
 [0.00179282 0.8152424  0.1740621  0.00890259]
 [0.0019054  0.9976299  0.0001287  0.00033593]
 [0.00005159 0.00023472 0.9989857  0.00072797]
 [0.00048878 0.99805874 0.00129541 0.00015711]
 [0.6704718  0.31965953 0.00188598 0.00798269]
 [0.6714527  0.32413247 0.00100173 0.00341313]
 [0.9116199  0.08286789 0.00507709 0.00043501]
 [0.00038362 0.9564506  0.04235711 0.00080869]
 [0.9995552  0.00026871 0.0001331  0.00004296]
 [0.22172478 0.77586263 0.00105864 0.00135399]
 [0.99826825 0.00024214 0.00050272 0.00098687]
 [0.9970668  0.00114959 0.00018616 0.00159749]
 [0.00462411 0.9931346  0.0004605  0.00178077]
 [0.0018503  0.9974995  0.00042128 0.00022891]
 [0.9962859  

In [37]:
#cnt2 = np.array([0,0,0,0])
#DET2(test2=test_up2)
#print(cnt2)

In [38]:
#pred.shape

In [39]:
'''
for i in range (pred.shape[0]):
    for j in range (4):
        if max(pred[i,:]) == pred[i,j]:
            cnt[j] += 1
    #print(max(pred[i,:]))
print(cnt)
'''

'\nfor i in range (pred.shape[0]):\n    for j in range (4):\n        if max(pred[i,:]) == pred[i,j]:\n            cnt[j] += 1\n    #print(max(pred[i,:]))\nprint(cnt)\n'

In [40]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/up_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(84, 45)
(84, 45)


In [41]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(84, 4)
[[0.9993399  0.00043532 0.00014567 0.00007919]
 [0.99553204 0.00324243 0.00022628 0.00099923]
 [0.99926287 0.00048788 0.00010053 0.00014867]
 [0.9985232  0.0007012  0.00014771 0.00062794]
 [0.9993167  0.00048205 0.00010264 0.00009866]
 [0.99903226 0.00075328 0.00010596 0.00010853]
 [0.9995509  0.00025781 0.00012456 0.00006666]
 [0.99956065 0.00021225 0.00012358 0.00010354]
 [0.9992488  0.00041528 0.0001521  0.00018379]
 [0.9996588  0.00008545 0.00015071 0.00010508]
 [0.99951756 0.00023753 0.00010824 0.00013674]
 [0.99859315 0.0010217  0.00016697 0.00021808]
 [0.99895096 0.00052061 0.00013779 0.00039064]
 [0.99167365 0.00750935 0.00050116 0.00031584]
 [0.99736744 0.0014081  0.00016637 0.00105819]
 [0.9993717  0.00038122 0.00012103 0.00012607]
 [0.99899393 0.00063912 0.0002202  0.00014676]
 [0.99940217 0.00033632 0.00016356 0.000098  ]
 [0.999213   0.00058338 0.00014254 0.00006102]
 [0.04347412 0.94386417 0.00076085 0.01190079]
 [0.9996226  0.00016248 0.00014684 0.00006812]
 [0.0

In [42]:
#cnt2 = np.array([0,0,0,0])
#DET2()
#print(cnt2)

In [43]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/left_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(83, 45)
(83, 45)


In [44]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(83, 4)
[[0.00002911 0.9991111  0.00058386 0.00027601]
 [0.00009364 0.9993851  0.00025726 0.000264  ]
 [0.00015634 0.98994046 0.0094644  0.00043877]
 [0.00006346 0.99919325 0.00049673 0.00024655]
 [0.00004479 0.9992607  0.00057539 0.00011909]
 [0.00012885 0.9993734  0.00021841 0.0002793 ]
 [0.00329804 0.99543214 0.00014189 0.00112789]
 [0.00023988 0.99914455 0.00015083 0.00046477]
 [0.00016042 0.9987312  0.00019176 0.00091665]
 [0.00003559 0.9992244  0.00058757 0.00015244]
 [0.00120063 0.99846315 0.00017714 0.00015905]
 [0.00007963 0.99926835 0.0002116  0.00044052]
 [0.85391855 0.14446838 0.00073755 0.00087552]
 [0.00023174 0.9994006  0.00016136 0.00020633]
 [0.00046414 0.9991603  0.00012566 0.00024988]
 [0.00006926 0.99954104 0.0002435  0.0001463 ]
 [0.00025132 0.99934584 0.00034919 0.0000536 ]
 [0.00004797 0.99950993 0.00033474 0.00010732]
 [0.00083192 0.9987355  0.00016058 0.00027205]
 [0.08077023 0.8976414  0.00040805 0.0211803 ]
 [0.00014984 0.99952424 0.00023038 0.00009548]
 [0.0

In [45]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/left_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(69, 45)
(69, 45)


In [46]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(69, 4)
[[0.19205    0.7792407  0.00107467 0.02763462]
 [0.02618014 0.95756286 0.0006347  0.01562229]
 [0.00011908 0.9994671  0.00014481 0.00026913]
 [0.05096445 0.9263662  0.00077495 0.02189442]
 [0.0001071  0.9986957  0.00095969 0.00023749]
 [0.00007244 0.9995895  0.00025818 0.0000799 ]
 [0.0002198  0.9989209  0.00009841 0.00076087]
 [0.00012159 0.00029266 0.00023693 0.9993488 ]
 [0.9434992  0.04664629 0.0007121  0.00914246]
 [0.00005178 0.9995142  0.00031505 0.00011889]
 [0.00007835 0.9993529  0.00017486 0.00039387]
 [0.00003319 0.9990312  0.0007026  0.00023301]
 [0.0000551  0.9993261  0.00049644 0.00012246]
 [0.00004221 0.9994529  0.00038273 0.0001222 ]
 [0.00024742 0.9992693  0.00008248 0.00040085]
 [0.0000665  0.99961096 0.00020498 0.00011761]
 [0.00003839 0.9994584  0.00039519 0.00010805]
 [0.00010101 0.99953127 0.00023205 0.00013569]
 [0.00030907 0.9992982  0.0001006  0.00029204]
 [0.00004621 0.99943286 0.00037702 0.00014393]
 [0.00018289 0.9994893  0.00014099 0.00018674]
 [0.0

In [47]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/back_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(71, 45)
(71, 45)


In [48]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(71, 4)
[[0.00017838 0.00074118 0.00033946 0.998741  ]
 [0.00245177 0.00267296 0.00158247 0.9932928 ]
 [0.00004645 0.00025369 0.00019354 0.99950635]
 [0.00066489 0.00186809 0.00084742 0.9966196 ]
 [0.00038029 0.0031207  0.00052951 0.99596953]
 [0.00026456 0.02826046 0.00393991 0.96753514]
 [0.00001807 0.00020351 0.0022564  0.99752206]
 [0.00002931 0.00018407 0.00021116 0.99957544]
 [0.00003809 0.00017612 0.00021541 0.9995703 ]
 [0.00017374 0.02902547 0.32560673 0.645194  ]
 [0.00001269 0.00020251 0.00040402 0.9993808 ]
 [0.00001235 0.00030387 0.00060764 0.9990761 ]
 [0.00003239 0.00016659 0.00016935 0.99963164]
 [0.00001437 0.00025258 0.0007029  0.9990301 ]
 [0.00002361 0.00018627 0.00021431 0.9995758 ]
 [0.00003126 0.00015338 0.00020197 0.99961346]
 [0.00003502 0.00696264 0.00092462 0.99207777]
 [0.00004614 0.99639267 0.00091686 0.00264437]
 [0.00002049 0.00056381 0.00300833 0.99640733]
 [0.00006207 0.00019814 0.00634279 0.993397  ]
 [0.00003143 0.00015145 0.00017905 0.99963796]
 [0.0

In [49]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/back_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(80, 45)
(80, 45)


In [50]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(80, 4)
[[0.00009048 0.00073041 0.00501512 0.99416393]
 [0.00146512 0.588133   0.35798812 0.05241375]
 [0.00004409 0.00015652 0.00029682 0.99950254]
 [0.00049365 0.02485593 0.6893019  0.28534847]
 [0.00002836 0.00011489 0.00061472 0.99924195]
 [0.00002483 0.00008151 0.00167675 0.9982168 ]
 [0.00001644 0.00007233 0.00160946 0.99830174]
 [0.00002592 0.00009883 0.00119489 0.9986803 ]
 [0.00017875 0.9258317  0.0037927  0.07019679]
 [0.00001822 0.00007057 0.00122054 0.99869066]
 [0.00003382 0.00017343 0.00014201 0.9996507 ]
 [0.00005304 0.00017846 0.00028084 0.99948764]
 [0.00002647 0.00021087 0.00056506 0.99919766]
 [0.00003743 0.0001285  0.00520267 0.9946314 ]
 [0.00007303 0.00072892 0.00041844 0.9987797 ]
 [0.00015483 0.00022574 0.39206922 0.6075502 ]
 [0.00001986 0.00029995 0.00042964 0.9992505 ]
 [0.00012663 0.00141113 0.00137263 0.9970897 ]
 [0.00238652 0.00669229 0.00053062 0.99039054]
 [0.00150571 0.00548079 0.00065255 0.992361  ]
 [0.00005083 0.00005983 0.99916315 0.00072626]
 [0.0

In [51]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/right_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
cnt = np.array([0,0,0,0])
CNT()
print(cnt)

(67, 45)
(67, 45)
(67, 4)
[[0.00013748 0.00026666 0.9993801  0.00021572]
 [0.00004317 0.00007431 0.999658   0.00022457]
 [0.00045439 0.0007447  0.9985826  0.00021836]
 [0.00008212 0.00016189 0.99950695 0.00024908]
 [0.00023112 0.00029158 0.99928623 0.00019105]
 [0.00005664 0.0001113  0.9996123  0.00021991]
 [0.00011233 0.00019697 0.99947983 0.0002109 ]
 [0.00006225 0.0001021  0.99963033 0.00020535]
 [0.0000797  0.00014641 0.9995604  0.00021341]
 [0.00009717 0.00022299 0.99950445 0.00017543]
 [0.00004377 0.00007153 0.9996283  0.00025637]
 [0.00005956 0.00027167 0.9967013  0.00296737]
 [0.00004367 0.00028321 0.9987196  0.0009535 ]
 [0.00016675 0.9984491  0.00117378 0.00021033]
 [0.0000597  0.00067163 0.994476   0.00479268]
 [0.00004214 0.00007932 0.9996202  0.00025832]
 [0.00005001 0.00008133 0.9995721  0.00029659]
 [0.00004223 0.00007406 0.999688   0.00019572]
 [0.00004325 0.00008058 0.9996014  0.00027481]
 [0.00004837 0.0000781  0.9996474  0.00022617]
 [0.00004616 0.00007482 0.99965596

In [52]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/half/right_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
cnt = np.array([0,0,0,0])
CNT()
print(cnt)

(74, 45)
(74, 45)
(74, 4)
[[0.00005078 0.00025394 0.99897444 0.00072078]
 [0.00004543 0.00013591 0.9994535  0.00036518]
 [0.00004407 0.00007823 0.9996418  0.00023593]
 [0.00004212 0.00009567 0.9995772  0.000285  ]
 [0.00017492 0.00106794 0.2035283  0.7952289 ]
 [0.00004375 0.0000783  0.99963915 0.00023886]
 [0.00007103 0.00034988 0.9986707  0.00090836]
 [0.00042709 0.03460585 0.95837486 0.00659223]
 [0.00004353 0.00007979 0.9996344  0.00024232]
 [0.00061466 0.30019835 0.65445983 0.04472712]
 [0.00006065 0.00049325 0.9980653  0.00138082]
 [0.00004448 0.00009878 0.99953556 0.00032121]
 [0.00039406 0.01128103 0.9860023  0.00232263]
 [0.00004217 0.00008527 0.9996332  0.0002394 ]
 [0.00008433 0.00027205 0.9993728  0.00027096]
 [0.00005297 0.0004794  0.9886205  0.01084717]
 [0.00002056 0.00023427 0.0018754  0.99786973]
 [0.00004673 0.00008363 0.9996056  0.00026402]
 [0.00004542 0.00008467 0.99960667 0.0002632 ]
 [0.00004247 0.00008015 0.99962413 0.00025317]
 [0.00004229 0.00007899 0.9996438 