In [1]:
from keras.models import load_model
from keras.preprocessing import sequence
import numpy as np
import pandas as pd

Using TensorFlow backend.
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lab606a/.virtualenvs

In [2]:
model = load_model('./saved model/classifier20200225')

In [50]:
maxlen = 144

In [51]:
def CNT():
    for i in range (pred.shape[0]):
        for j in range (4):
            if max(pred[i,:]) == pred[i,j]:
                cnt[j] += 1

In [126]:
def DET(traj):
    for i in range(15,46,3):
        test = test_up2[traj,:]
        test = test.reshape(1,test.shape[0])
        #print(test.shape)
        tmp = test[:,:i]
        tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
        #print(tmp)
        pred = model.predict(tmp)
        np.set_printoptions(suppress=True)
        #print(pred)
        print("number of balls =", int(i/3), ", probability =", pred)
        
        if max(pred[0,:]) == pred[:,0]:
            print("top spin")
        elif max(pred[0,:]) == pred[:,1]:
            print("left spin")
        elif max(pred[0,:]) == pred[:,2]:
            print("right spin")
        elif max(pred[0,:]) == pred[:,3]:
            print("back spin")
        

In [144]:
def DET2(test2):
    for j in range(test2.shape[0]):
        print("trajectory", j)
        for i in range(15,maxlen,3):
            test = test2[4,:]
            test = test.reshape(1,test.shape[0])
            tmp = test[:,:i]
            tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
            pred = model.predict(tmp)
            np.set_printoptions(suppress=True)
            #print(pred)
            print("number of balls =", int(i/3), ", probability =", pred)
        
            if max(pred[0,:]) == pred[:,0]:
                print("top spin")
            elif max(pred[0,:]) == pred[:,1]:
                print("left spin")
            elif max(pred[0,:]) == pred[:,2]:
                print("right spin")
            elif max(pred[0,:]) == pred[:,3]:
                print("back spin")
                
        print("--------------------------")
        if max(pred[0,:]) == pred[:,0]:
            cnt2[0] += 1
        elif max(pred[0,:]) == pred[:,1]:
            cnt2[1] += 1
        elif max(pred[0,:]) == pred[:,2]:
            cnt2[2] += 1
        elif max(pred[0,:]) == pred[:,3]:
            cnt2[3] += 1

In [148]:
cnt = np.array([0,0,0,0])

In [131]:
cnt2 = np.array([0,0,0,0])

In [146]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/up_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
test_up2.shape
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
test_up2.shape

(83, 144)

In [149]:
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred)
CNT()
print(cnt)

[[0.47606918 0.00187673 0.52137053 0.00068356]
 [0.52607214 0.00142529 0.47170657 0.00079594]
 [0.793891   0.00169342 0.20405322 0.0003624 ]
 [0.69706774 0.00099665 0.3012615  0.00067409]
 [0.9994288  0.00003997 0.00035114 0.00017999]
 [0.9981394  0.0000545  0.00099261 0.00081353]
 [0.8809725  0.00104615 0.11768147 0.00029987]
 [0.04744756 0.00072893 0.9479527  0.0038707 ]
 [0.9994222  0.00004384 0.00037359 0.00016041]
 [0.9673361  0.00039783 0.03172136 0.00054474]
 [0.13951457 0.15777117 0.70203024 0.00068395]
 [0.9993505  0.00005112 0.00046659 0.0001318 ]
 [0.9992149  0.00005832 0.0005891  0.00013758]
 [0.9992755  0.00004142 0.00043517 0.00024784]
 [0.998544   0.00004874 0.00079228 0.00061504]
 [0.99943334 0.00004144 0.00035158 0.0001736 ]
 [0.99942756 0.00004694 0.00040059 0.00012495]
 [0.99851936 0.00004904 0.00080532 0.0006263 ]
 [0.9991429  0.00004186 0.00050038 0.00031494]
 [0.9982158  0.00009101 0.00155729 0.00013587]
 [0.9994343  0.00004254 0.00035837 0.0001648 ]
 [0.96119565 

In [159]:
rrr = test_up2[0, :]
rrr = rrr.reshape(1, maxlen)
rrr = rrr[:, :]
rrr = sequence.pad_sequences(rrr, maxlen=maxlen, padding='post')
p = model.predict(rrr)
print(p)

[[0.99931514 0.00004406 0.00042634 0.00021442]]


In [145]:
cnt2 = np.array([0,0,0,0])
DET2(test2=test_up2)
print(cnt2)

trajectory 0
number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.0

number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.000

number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00

number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.0

number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.

number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0

number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  

number of balls = 11 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 

number of balls = 12 , probability = [[0.0022114  0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 

number of balls = 13 , probability = [[0.00221142 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  

number of balls = 14 , probability = [[0.00206018 0.00035401 0.00583411 0.99175173]]
back spin
number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 

number of balls = 15 , probability = [[0.00221279 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 

number of balls = 16 , probability = [[0.00221285 0.00026712 0.00205058 0.99546945]]
back spin
number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  

number of balls = 17 , probability = [[0.0022127  0.00026712 0.00205052 0.9954697 ]]
back spin
number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0

number of balls = 18 , probability = [[0.00221249 0.00026712 0.00205043 0.9954699 ]]
back spin
number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.

number of balls = 19 , probability = [[0.00221248 0.00026713 0.00205041 0.99547005]]
back spin
number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0

number of balls = 20 , probability = [[0.0022123  0.00026713 0.00205033 0.99547017]]
back spin
number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00

number of balls = 21 , probability = [[0.00221202 0.00026713 0.00205026 0.99547064]]
back spin
number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.000

number of balls = 22 , probability = [[0.00221185 0.00026713 0.00205042 0.99547064]]
back spin
number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.0000

number of balls = 23 , probability = [[0.0022118  0.00026713 0.00205054 0.99547064]]
back spin
number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004

number of balls = 24 , probability = [[0.00221177 0.00026714 0.00205061 0.9954705 ]]
back spin
number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.000039

number of balls = 25 , probability = [[0.00221284 0.00026711 0.00205056 0.99546945]]
back spin
number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.0000399

number of balls = 26 , probability = [[0.9619133  0.00038921 0.00640518 0.03129234]]
top spin
number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997

number of balls = 27 , probability = [[0.984772   0.00021258 0.0044568  0.0105586 ]]
top spin
number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997

number of balls = 28 , probability = [[0.9897788  0.0001623  0.00353905 0.00651981]]
top spin
number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997

number of balls = 29 , probability = [[0.9929368  0.0001258  0.00262392 0.00431347]]
top spin
number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997

number of balls = 30 , probability = [[0.99647886 0.00007775 0.00151363 0.00192974]]
top spin
number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997

number of balls = 31 , probability = [[0.9979796  0.00005669 0.00104986 0.00091383]]
top spin
number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997

number of balls = 32 , probability = [[0.99866986 0.00004688 0.00073379 0.00054942]]
top spin
number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997

number of balls = 33 , probability = [[0.99921167 0.00004103 0.00046526 0.00028208]]
top spin
number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997

number of balls = 34 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997

number of balls = 35 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997

number of balls = 36 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997

number of balls = 37 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997

number of balls = 38 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
trajectory 69
number of balls = 5

number of balls = 39 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
trajectory 71
number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6

number of balls = 40 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
trajectory 73
number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7

number of balls = 41 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
trajectory 75
number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8

number of balls = 42 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
trajectory 77
number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9

number of balls = 43 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
trajectory 79
number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 1

number of balls = 44 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
trajectory 81
number of balls = 5 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.0002671  0.00204998 0.9954715 ]]
back spin
number of balls = 

number of balls = 45 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 46 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
number of balls = 47 , probability = [[0.9994288  0.00003997 0.00035114 0.00017999]]
top spin
--------------------------
[83  0  0  0]


In [56]:
#pred.shape

In [57]:
'''
for i in range (pred.shape[0]):
    for j in range (4):
        if max(pred[i,:]) == pred[i,j]:
            cnt[j] += 1
    #print(max(pred[i,:]))
print(cnt)
'''

'\nfor i in range (pred.shape[0]):\n    for j in range (4):\n        if max(pred[i,:]) == pred[i,j]:\n            cnt[j] += 1\n    #print(max(pred[i,:]))\nprint(cnt)\n'

In [136]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/up_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(84, 102)
(84, 144)


In [137]:
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(84, 4)
[[0.99940825 0.00004057 0.0003609  0.00019026]
 [0.99938023 0.00004209 0.00038206 0.00019564]
 [0.9993481  0.00004206 0.00040006 0.00020983]
 [0.99800295 0.00005823 0.00092667 0.00101217]
 [0.9993331  0.00004089 0.00040201 0.00022398]
 [0.99930084 0.00004172 0.00042153 0.00023597]
 [0.999019   0.00004319 0.00056142 0.00037633]
 [0.9991573  0.000043   0.00050562 0.00029404]
 [0.9989513  0.00004371 0.00059745 0.00040746]
 [0.9992126  0.00004224 0.00047338 0.00027173]
 [0.9990646  0.00004255 0.00054002 0.00035285]
 [0.9989484  0.00004353 0.00059746 0.00041057]
 [0.9985482  0.00005038 0.0007132  0.00068821]
 [0.9994288  0.00004236 0.00036116 0.00016762]
 [0.9988827  0.00004408 0.00062045 0.00045284]
 [0.999268   0.00004173 0.00043899 0.00025128]
 [0.9981219  0.00005469 0.00098623 0.00083711]
 [0.998847   0.00004451 0.00064395 0.00046449]
 [0.99866164 0.00004712 0.00073746 0.00055374]
 [0.99778914 0.00005941 0.00114668 0.00100482]
 [0.0922892  0.00080775 0.8928255  0.01407761]
 [0.9

In [138]:
cnt2 = np.array([0,0,0,0])
DET2()
print(cnt2)

trajectory 0
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.0

number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 8
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls

number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 16
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of bal

number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 24
number of bal

number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 31
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of ball

number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 39
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of bal

number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.000

number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 54
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of ball

number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 62
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of bal

number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 69
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 10 , probability = [[0.0022114  0.00026711 0.00205    0.9954715 ]]
back spin
number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of ball

number of balls = 11 , probability = [[0.00221141 0.00026712 0.00205002 0.9954715 ]]
back spin
number of balls = 12 , probability = [[0.00221144 0.00026714 0.00205007 0.9954715 ]]
back spin
number of balls = 13 , probability = [[0.00221147 0.00026716 0.00205012 0.99547124]]
back spin
number of balls = 14 , probability = [[0.00221159 0.00026724 0.00205033 0.99547076]]
back spin
number of balls = 15 , probability = [[0.00222139 0.00027727 0.00207782 0.9954235 ]]
back spin
--------------------------
trajectory 77
number of balls = 5 , probability = [[0.00221139 0.00026711 0.00204999 0.9954715 ]]
back spin
number of balls = 6 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 7 , probability = [[0.0022114  0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 8 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of balls = 9 , probability = [[0.00221139 0.0002671  0.00204999 0.9954715 ]]
back spin
number of ball

In [60]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/left_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(83, 135)
(83, 144)


In [61]:
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(83, 4)
[[0.00016526 0.9837684  0.0135987  0.00246763]
 [0.00052975 0.07766155 0.9207486  0.00106011]
 [0.00133491 0.32735708 0.6671536  0.0041544 ]
 [0.0007232  0.5090017  0.48538426 0.00489083]
 [0.00216528 0.8010843  0.19040428 0.00634609]
 [0.00005511 0.83820957 0.14729013 0.01444522]
 [0.00003607 0.99099267 0.00737531 0.00159608]
 [0.0000497  0.9770208  0.01908684 0.0038426 ]
 [0.00011418 0.9964948  0.00118837 0.00220262]
 [0.00012387 0.9941566  0.00332084 0.00239876]
 [0.00117416 0.86101526 0.13699318 0.0008174 ]
 [0.00035762 0.8017432  0.19699106 0.00090809]
 [0.00121584 0.35305804 0.00395753 0.64176863]
 [0.00005074 0.9974037  0.00155918 0.00098636]
 [0.00018237 0.9909547  0.00845573 0.00040711]
 [0.0006652  0.688626   0.00383259 0.30687618]
 [0.00005938 0.997189   0.00210348 0.00064805]
 [0.00011351 0.9485387  0.05033738 0.00101039]
 [0.00005023 0.9702454  0.01480274 0.0149016 ]
 [0.00052288 0.00283498 0.99652207 0.00012004]
 [0.00030778 0.01380393 0.98572844 0.00015976]
 [0.0

In [62]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/left_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(69, 114)
(69, 144)


In [63]:
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(69, 4)
[[0.00612646 0.9657844  0.02778205 0.00030715]
 [0.00029007 0.9928477  0.0066303  0.00023191]
 [0.00011701 0.99737227 0.00228895 0.00022174]
 [0.00050506 0.9943356  0.00495077 0.00020853]
 [0.00041345 0.9884326  0.01099456 0.00015936]
 [0.00006702 0.9982139  0.00148766 0.00023144]
 [0.00015096 0.98671967 0.01234855 0.00078088]
 [0.00028555 0.82412577 0.11343212 0.06215647]
 [0.00009797 0.997623   0.00210407 0.00017493]
 [0.00057959 0.99075985 0.00847745 0.00018321]
 [0.00009672 0.9844758  0.01067296 0.00475451]
 [0.00007936 0.12556447 0.8719626  0.00239352]
 [0.00021629 0.84628296 0.12996769 0.02353306]
 [0.0000909  0.9971265  0.0026071  0.00017549]
 [0.00008167 0.99808526 0.00163642 0.00019666]
 [0.00006548 0.9978034  0.00183572 0.00029536]
 [0.00007285 0.9981059  0.00162629 0.00019504]
 [0.00006601 0.9980101  0.00151161 0.00041231]
 [0.00006499 0.99824846 0.00142486 0.00026174]
 [0.00006006 0.99815565 0.00150505 0.00027917]
 [0.00006739 0.9982564  0.00143169 0.00024457]
 [0.0

In [64]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/back_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(71, 132)
(71, 144)


In [65]:
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(71, 4)
[[0.00041669 0.00862934 0.06740233 0.9235517 ]
 [0.00123528 0.00063557 0.00952304 0.98860604]
 [0.00207111 0.00036242 0.00563282 0.99193364]
 [0.00046911 0.00687849 0.05445008 0.9382024 ]
 [0.00079862 0.00204428 0.00098243 0.9961746 ]
 [0.00069654 0.00133825 0.00182892 0.99613625]
 [0.00088426 0.00098747 0.0016535  0.9964747 ]
 [0.00058476 0.00133665 0.00188156 0.9961971 ]
 [0.00118174 0.00296878 0.00703089 0.9888186 ]
 [0.00097366 0.00081238 0.00140476 0.9968092 ]
 [0.00110489 0.02311643 0.00215237 0.97362626]
 [0.00091521 0.00413742 0.00166311 0.9932842 ]
 [0.0009917  0.00221299 0.00130224 0.99549305]
 [0.00096356 0.00241443 0.00146364 0.9951584 ]
 [0.00028422 0.00116813 0.00169173 0.99685585]
 [0.00242277 0.0004863  0.00196782 0.9951231 ]
 [0.00079511 0.00150018 0.00157844 0.99612635]
 [0.00098312 0.10440107 0.1340022  0.76061356]
 [0.00121932 0.00130327 0.00180371 0.9956737 ]
 [0.00058402 0.00903589 0.8375426  0.15283743]
 [0.00152223 0.00114427 0.0019062  0.99542725]
 [0.0

In [66]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/back_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(80, 114)
(80, 144)


In [67]:
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(80, 4)
[[0.00036247 0.00075725 0.00143221 0.9974481 ]
 [0.00169706 0.00798931 0.502637   0.48767662]
 [0.00046681 0.00143833 0.0065996  0.99149525]
 [0.00218248 0.00030509 0.00317725 0.9943351 ]
 [0.0003513  0.00129188 0.00371717 0.9946397 ]
 [0.0022121  0.00026752 0.00205096 0.99546945]
 [0.00038088 0.00079161 0.00146019 0.99736744]
 [0.00051404 0.00108914 0.00164697 0.9967499 ]
 [0.0003489  0.0009389  0.00162296 0.9970893 ]
 [0.00029932 0.00376731 0.00161294 0.9943204 ]
 [0.0022132  0.0002683  0.00205564 0.99546283]
 [0.00221035 0.00026762 0.00206564 0.99545634]
 [0.00035833 0.00087609 0.00141584 0.9973496 ]
 [0.00192981 0.0004186  0.01061468 0.9870368 ]
 [0.00184169 0.00046062 0.01502415 0.98267347]
 [0.0018283  0.00046598 0.0156872  0.9820186 ]
 [0.00183171 0.00046466 0.01552632 0.98217726]
 [0.00036391 0.00076509 0.00145364 0.99741733]
 [0.00210941 0.0003312  0.00457951 0.99297994]
 [0.00053242 0.00180363 0.01042693 0.987237  ]
 [0.00191793 0.00042502 0.01119762 0.9864594 ]
 [0.0

In [68]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/right_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(67, 132)
(67, 144)
(67, 4)
[[0.00251211 0.25030634 0.7438649  0.00331664]
 [0.00117829 0.00252975 0.99598336 0.00030863]
 [0.00018887 0.00186118 0.9976603  0.00028975]
 [0.00034605 0.00047056 0.9988925  0.00029091]
 [0.00025766 0.00053917 0.9989716  0.00023158]
 [0.00043781 0.00142887 0.99802125 0.00011207]
 [0.00022881 0.0006844  0.9988778  0.00020898]
 [0.00050637 0.00130457 0.9980925  0.00009656]
 [0.00034618 0.00049699 0.99880004 0.00035683]
 [0.00063183 0.00033397 0.9983664  0.00066775]
 [0.00168737 0.01449053 0.95434904 0.02947296]
 [0.00202866 0.00053762 0.9962535  0.00118026]
 [0.0001569  0.00582848 0.9937388  0.00027592]
 [0.00007271 0.30435443 0.68639076 0.00918217]
 [0.00169965 0.0006411  0.99664897 0.0010103 ]
 [0.00098481 0.0051612  0.9920632  0.00179077]
 [0.01187391 0.0046848  0.27485943 0.70858186]
 [0.00192497 0.00153097 0.9963362  0.00020788]
 [0.04609901 0.00045446 0.9445532  0.00889331]
 [0.00019488 0.01197782 0.00733583 0.9804914 ]
 [0.00021419 0.0010602  0.998485

In [69]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/right_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(74, 111)
(74, 144)
(74, 4)
[[0.00014795 0.05328561 0.9421598  0.00440664]
 [0.00047721 0.00054325 0.9972083  0.00177131]
 [0.00059663 0.00042654 0.99800974 0.00096717]
 [0.00093004 0.00040274 0.9954137  0.00325343]
 [0.00052168 0.00115813 0.9936506  0.00466968]
 [0.00315403 0.00028276 0.9937057  0.00285749]
 [0.00047763 0.00317621 0.98448884 0.01185731]
 [0.00021118 0.05853647 0.926228   0.0150244 ]
 [0.00021477 0.0016015  0.9964484  0.00173529]
 [0.00047215 0.00229009 0.99097085 0.0062669 ]
 [0.00038974 0.00066387 0.99730635 0.00164005]
 [0.00147689 0.00031173 0.9961623  0.00204909]
 [0.00077443 0.00093674 0.9919743  0.00631453]
 [0.00086638 0.00040724 0.99573743 0.00298885]
 [0.00076183 0.00043156 0.99619555 0.00261103]
 [0.00124155 0.0003438  0.99510574 0.00330899]
 [0.00055766 0.00046529 0.9976203  0.00135673]
 [0.00093012 0.00038485 0.99638236 0.00230258]
 [0.00075464 0.00043515 0.99622107 0.00258906]
 [0.00040014 0.00051154 0.9983658  0.00072256]
 [0.00108458 0.00036401 0.995290