In [1]:
from keras.models import load_model
from keras.preprocessing import sequence
import numpy as np
import pandas as pd

Using TensorFlow backend.
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lab606a/.virtualenvs

In [2]:
model = load_model('./saved model/classifier20200226_20')

In [3]:
maxlen = 60

In [4]:
def CNT():
    for i in range (pred.shape[0]):
        for j in range (4):
            if max(pred[i,:]) == pred[i,j]:
                cnt[j] += 1

In [5]:
def DET(traj):
    for i in range(3,maxlen,3):
        test = test_up2[traj,:]
        test = test.reshape(1,test.shape[0])
        #print(test.shape)
        tmp = test[:,:i]
        tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
        #print(tmp)
        pred = model.predict(tmp)
        np.set_printoptions(suppress=True)
        #print(pred)
        print("number of balls =", int(i/3), ", probability =", pred)
        
        if max(pred[0,:]) == pred[:,0]:
            print("top spin")
        elif max(pred[0,:]) == pred[:,1]:
            print("left spin")
        elif max(pred[0,:]) == pred[:,2]:
            print("right spin")
        elif max(pred[0,:]) == pred[:,3]:
            print("back spin")
        

In [6]:
def DET2(test2):
    for j in range(test2.shape[0]):
        print("trajectory", j)
        for i in range(3,maxlen,3):
            test = test2[4,:]
            test = test.reshape(1,test.shape[0])
            tmp = test[:,:i]
            tmp = sequence.pad_sequences(tmp, maxlen=maxlen, padding='post')
            pred = model.predict(tmp)
            np.set_printoptions(suppress=True)
            #print(pred)
            print("number of balls =", int(i/3), ", probability =", pred)
        
            if max(pred[0,:]) == pred[:,0]:
                print("top spin")
            elif max(pred[0,:]) == pred[:,1]:
                print("left spin")
            elif max(pred[0,:]) == pred[:,2]:
                print("right spin")
            elif max(pred[0,:]) == pred[:,3]:
                print("back spin")
                
        print("--------------------------")
        if max(pred[0,:]) == pred[:,0]:
            cnt2[0] += 1
        elif max(pred[0,:]) == pred[:,1]:
            cnt2[1] += 1
        elif max(pred[0,:]) == pred[:,2]:
            cnt2[2] += 1
        elif max(pred[0,:]) == pred[:,3]:
            cnt2[3] += 1

In [7]:
cnt = np.array([0,0,0,0])

In [8]:
cnt2 = np.array([0,0,0,0])

In [9]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/up_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
test_up2.shape
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
test_up2.shape

(83, 60)

In [10]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred)
CNT()
print(cnt)

[[0.00000465 0.00014871 0.00005831 0.99978834]
 [0.00002528 0.00047865 0.99907506 0.00042096]
 [0.00002542 0.00054005 0.99853384 0.00090075]
 [0.00000319 0.00009678 0.0000775  0.99982256]
 [0.00023239 0.9694435  0.00781925 0.0225049 ]
 [0.00007316 0.00210566 0.97616094 0.02166014]
 [0.00000145 0.00006945 0.00019024 0.9997389 ]
 [0.0048619  0.9948251  0.00013627 0.0001767 ]
 [0.19178368 0.8074951  0.00045899 0.00026224]
 [0.00000318 0.00009336 0.0000912  0.9998123 ]
 [0.00059847 0.99925476 0.00002731 0.00011949]
 [0.9485261  0.04115273 0.01017109 0.00015008]
 [0.99857926 0.00133342 0.00007067 0.00001677]
 [0.9918372  0.00754131 0.00059236 0.00002908]
 [0.00005555 0.9997851  0.00005581 0.00010351]
 [0.00071874 0.99913687 0.00003052 0.000114  ]
 [0.00012106 0.9997626  0.00002536 0.00009093]
 [0.1816847  0.81723624 0.00084374 0.00023532]
 [0.99765563 0.00226773 0.00006531 0.00001127]
 [0.05223285 0.94714624 0.00039091 0.00022994]
 [0.99063    0.00918676 0.00015831 0.00002501]
 [0.98871624 

In [11]:
#cnt2 = np.array([0,0,0,0])
#DET2(test2=test_up2)
#print(cnt2)

In [12]:
#pred.shape

In [13]:
'''
for i in range (pred.shape[0]):
    for j in range (4):
        if max(pred[i,:]) == pred[i,j]:
            cnt[j] += 1
    #print(max(pred[i,:]))
print(cnt)
'''

'\nfor i in range (pred.shape[0]):\n    for j in range (4):\n        if max(pred[i,:]) == pred[i,j]:\n            cnt[j] += 1\n    #print(max(pred[i,:]))\nprint(cnt)\n'

In [14]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/up_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(84, 60)
(84, 60)


In [15]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(84, 4)
[[0.9996557  0.00025868 0.00007437 0.00001117]
 [0.8634935  0.13611946 0.00032541 0.00006165]
 [0.9995952  0.00032063 0.00007111 0.00001308]
 [0.99966216 0.00027264 0.00005512 0.00001005]
 [0.9992136  0.00070501 0.000068   0.00001335]
 [0.99965334 0.00026515 0.00006922 0.00001234]
 [0.99966216 0.00026315 0.00006313 0.00001164]
 [0.9991749  0.00025394 0.00054324 0.0000279 ]
 [0.99898916 0.00091532 0.00008348 0.00001202]
 [0.99964726 0.00026599 0.00007362 0.00001314]
 [0.9996722  0.00025068 0.00006594 0.00001121]
 [0.9996489  0.00027908 0.00006037 0.00001164]
 [0.99959725 0.00034301 0.00005004 0.00000972]
 [0.99965346 0.00025595 0.00007904 0.00001159]
 [0.99967635 0.00024799 0.00006338 0.00001227]
 [0.99965465 0.00026146 0.00007136 0.00001254]
 [0.99967587 0.00024837 0.00006434 0.00001144]
 [0.9996742  0.00025948 0.00005517 0.00001124]
 [0.9996823  0.00025206 0.00005699 0.00000867]
 [0.9996269  0.00029233 0.00006951 0.00001133]
 [0.00199784 0.00008204 0.99774617 0.00017387]
 [0.9

In [16]:
#cnt2 = np.array([0,0,0,0])
#DET2()
#print(cnt2)

In [17]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/left_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(83, 60)
(83, 60)


In [18]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(83, 4)
[[0.00010108 0.9989215  0.00017915 0.00079827]
 [0.00029798 0.00307401 0.9908057  0.00582229]
 [0.00002975 0.00009541 0.9998024  0.0000725 ]
 [0.70883995 0.24318273 0.04705144 0.00092589]
 [0.05096696 0.00088754 0.9477976  0.00034789]
 [0.00017116 0.99971586 0.00003507 0.00007796]
 [0.00013251 0.9997881  0.00002402 0.00005537]
 [0.00013614 0.9997695  0.00002898 0.00006544]
 [0.00018476 0.9997261  0.00002425 0.00006486]
 [0.00015035 0.9997694  0.00002301 0.00005716]
 [0.00013234 0.99978656 0.00002274 0.00005837]
 [0.00019023 0.9997259  0.00002233 0.00006158]
 [0.00016345 0.9997309  0.00002973 0.00007583]
 [0.00014583 0.9997758  0.00001991 0.00005844]
 [0.0001461  0.99977356 0.00002547 0.00005489]
 [0.00016771 0.99970955 0.00003683 0.00008589]
 [0.00016099 0.99971634 0.0000314  0.00009126]
 [0.00016979 0.9997192  0.00002926 0.00008164]
 [0.00018104 0.9996424  0.00003261 0.00014405]
 [0.00027676 0.9990833  0.00021429 0.00042567]
 [0.00015671 0.9997571  0.0000282  0.00005792]
 [0.0

In [19]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/left_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(69, 60)
(69, 60)


In [20]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(69, 4)
[[0.0011112  0.9986903  0.00006349 0.00013493]
 [0.00024315 0.9996346  0.00003211 0.00009021]
 [0.00013548 0.99976534 0.00002329 0.00007589]
 [0.00012435 0.99977916 0.0000269  0.00006961]
 [0.00016449 0.9996958  0.00003699 0.00010284]
 [0.00013096 0.9997681  0.00002095 0.00008004]
 [0.00012813 0.9997904  0.00002402 0.00005755]
 [0.00013149 0.99978036 0.000025   0.00006319]
 [0.00188172 0.997926   0.00005271 0.00013955]
 [0.00015194 0.99976844 0.00002471 0.00005489]
 [0.00013332 0.99979144 0.00002186 0.0000533 ]
 [0.00009375 0.9995264  0.00006874 0.00031111]
 [0.00014237 0.99976677 0.00002842 0.00006244]
 [0.00015185 0.9997743  0.00002133 0.00005258]
 [0.00016001 0.99975723 0.00002006 0.0000626 ]
 [0.00013962 0.9997782  0.00002372 0.00005857]
 [0.00014056 0.9997677  0.00002197 0.00006981]
 [0.00013552 0.9997923  0.00002037 0.00005188]
 [0.00016974 0.9997528  0.00001498 0.00006247]
 [0.00016125 0.9997669  0.0000166  0.00005521]
 [0.00013518 0.9997937  0.00001653 0.00005467]
 [0.0

In [21]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/back_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(71, 60)
(71, 60)


In [22]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(71, 4)
[[0.0000097  0.00015544 0.00014365 0.99969125]
 [0.00001552 0.00016294 0.00016187 0.99965966]
 [0.00000483 0.00010348 0.00015756 0.9997341 ]
 [0.00000987 0.0001589  0.00012624 0.999705  ]
 [0.00240717 0.3518733  0.00015798 0.64556146]
 [0.00008047 0.05022818 0.00009118 0.9496001 ]
 [0.00000996 0.00012079 0.00026185 0.9996075 ]
 [0.0000062  0.00018205 0.00006668 0.9997451 ]
 [0.00000507 0.00012932 0.00007382 0.9997918 ]
 [0.00005541 0.05452466 0.00270081 0.9427191 ]
 [0.00000867 0.00041192 0.00009084 0.9994886 ]
 [0.00001567 0.00019843 0.00022435 0.9995615 ]
 [0.00000502 0.00014524 0.0000665  0.9997832 ]
 [0.00001019 0.0001339  0.00019065 0.99966526]
 [0.00000489 0.00040755 0.00008106 0.9995065 ]
 [0.00000411 0.00035683 0.00008386 0.9995552 ]
 [0.00000598 0.00326881 0.00006106 0.9966641 ]
 [0.00013696 0.9226865  0.0117408  0.06543582]
 [0.00000594 0.00012812 0.00009832 0.9997676 ]
 [0.00000684 0.00012227 0.00011206 0.9997589 ]
 [0.00000426 0.00012164 0.00006806 0.9998061 ]
 [0.0

In [23]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/back_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)

(80, 60)
(80, 60)


In [24]:
cnt = np.array([0,0,0,0])
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
CNT()
print(cnt)

(80, 4)
[[0.00000291 0.00056853 0.00034757 0.999081  ]
 [0.00000241 0.00029248 0.00033735 0.9993678 ]
 [0.00050721 0.00372787 0.6386888  0.3570761 ]
 [0.00000332 0.00038493 0.00013637 0.9994753 ]
 [0.00000161 0.00008577 0.00018671 0.9997259 ]
 [0.00000199 0.00008513 0.00007451 0.99983835]
 [0.00000201 0.00010274 0.00010119 0.99979407]
 [0.00000297 0.00011234 0.00005116 0.9998336 ]
 [0.00025126 0.7868525  0.00030273 0.2125935 ]
 [0.00000204 0.00015492 0.00008669 0.9997564 ]
 [0.00000342 0.00011358 0.00005789 0.99982506]
 [0.00000369 0.00010464 0.00007466 0.9998171 ]
 [0.00000382 0.00012427 0.00006159 0.9998103 ]
 [0.00000171 0.00006929 0.00012592 0.999803  ]
 [0.00000588 0.00014139 0.00009468 0.99975806]
 [0.00000879 0.00015917 0.00009664 0.9997354 ]
 [0.00001328 0.00017979 0.00011316 0.99969375]
 [0.00000647 0.00014153 0.00009599 0.99975604]
 [0.00000162 0.00006763 0.00010903 0.9998217 ]
 [0.00000136 0.00005444 0.00014785 0.99979633]
 [0.00072781 0.00164555 0.24853997 0.7490867 ]
 [0.0

In [25]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/right_speed5_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
cnt = np.array([0,0,0,0])
CNT()
print(cnt)

(67, 60)
(67, 60)
(67, 4)
[[0.00006593 0.00007787 0.99981076 0.00004538]
 [0.00016216 0.0000331  0.99977833 0.00002645]
 [0.00020341 0.00002509 0.999747   0.00002456]
 [0.00004174 0.00015654 0.99971133 0.00009039]
 [0.00004103 0.00016148 0.99971694 0.00008057]
 [0.00008278 0.00006228 0.99981636 0.00003861]
 [0.00005594 0.00010522 0.9997811  0.00005783]
 [0.00009008 0.00006102 0.9998074  0.00004152]
 [0.00006338 0.00012214 0.9997371  0.00007736]
 [0.00016071 0.00003438 0.9997782  0.00002675]
 [0.00007757 0.00099702 0.5752639  0.4236615 ]
 [0.00007233 0.00197032 0.9506893  0.04726797]
 [0.00016001 0.03327632 0.7327231  0.23384051]
 [0.00000806 0.00100749 0.00011441 0.99886996]
 [0.00002531 0.00012063 0.9997061  0.00014795]
 [0.00002958 0.00007994 0.9998135  0.00007705]
 [0.00011873 0.00045948 0.70679593 0.2926259 ]
 [0.00005574 0.00005266 0.99983835 0.00005331]
 [0.00005026 0.00029179 0.9973441  0.00231394]
 [0.00000679 0.00015025 0.00013261 0.99971026]
 [0.00039261 0.00002078 0.999556  

In [26]:
test_up2 = pd.read_csv('/home/lab606a/Documents/datasets/20/right_speed6_test.csv', header=None)
test_up2 = test_up2.fillna(0)
test_up2 = np.array(test_up2)
print(test_up2.shape)
test_up2 = sequence.pad_sequences(test_up2, maxlen=maxlen, padding='post')
print(test_up2.shape)
pred = model.predict(test_up2)
np.set_printoptions(suppress=True)
print(pred.shape)
print(pred)
cnt = np.array([0,0,0,0])
CNT()
print(cnt)

(74, 60)
(74, 60)
(74, 4)
[[0.00004407 0.00060211 0.99894613 0.00040779]
 [0.00005456 0.00004706 0.999859   0.00003931]
 [0.00004683 0.00007505 0.99983037 0.00004767]
 [0.00002779 0.00020003 0.9995486  0.00022355]
 [0.0000769  0.00255774 0.9861763  0.01118899]
 [0.0000561  0.0000786  0.9998184  0.00004699]
 [0.00002643 0.00034442 0.99912554 0.00050361]
 [0.00004249 0.00306524 0.9947214  0.00217084]
 [0.00002419 0.00011176 0.9997861  0.00007795]
 [0.00004536 0.00222184 0.9936035  0.00412925]
 [0.00002325 0.00009394 0.9998048  0.00007809]
 [0.00004314 0.00007908 0.99982774 0.00005001]
 [0.0001634  0.01675437 0.79352665 0.18955563]
 [0.00002791 0.00006422 0.99984944 0.00005839]
 [0.00002662 0.00011599 0.9997547  0.00010265]
 [0.00003525 0.00007447 0.9998354  0.00005495]
 [0.00008128 0.00003271 0.9998555  0.00003057]
 [0.00022372 0.00002235 0.99973184 0.00002199]
 [0.00014508 0.00003764 0.99978894 0.00002837]
 [0.00020245 0.00002454 0.9997497  0.00002322]
 [0.00002566 0.00009422 0.99980944