In [68]:
from __future__ import print_function

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.datasets import imdb

In [69]:
max_features = 20000
# cut texts after this number of words (among top max_features most common words)
maxlen = 80
batch_size = 32

In [70]:
import numpy as np
# save np.load
np_load_old = np.load

# modify the default parameters of np.load
np.load = lambda *a,**k: np_load_old(*a, allow_pickle=True, **k)

print('Loading data...')
# call load_data with allow_pickle implicitly set to true
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

# restore np.load for future normal usage
np.load = np_load_old

print(len(x_train), 'train sequences')
print(len(x_test), 'test sequences')

Loading data...
25000 train sequences
25000 test sequences


In [71]:
x_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,

In [72]:
len(x_train[4])

147

In [73]:
y_train.shape

(25000,)

In [74]:
print('Pad sequences (samples x time)')
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)

Pad sequences (samples x time)
x_train shape: (25000, 80)
x_test shape: (25000, 80)


In [75]:
x_train[0].shape

(80,)

In [76]:
print('Build model...')
model = Sequential()
model.add(Embedding(max_features, 128))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

Build model...


In [77]:
# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [78]:
print('Train...')
model.fit(x_train, y_train,
          batch_size=1000,
          epochs=5,
          validation_data=(x_test, y_test))
score, acc = model.evaluate(x_test, y_test,
                            batch_size=batch_size)
print('Test score:', score)
print('Test accuracy:', acc)

Train...
Train on 25000 samples, validate on 25000 samples
Epoch 1/5
25000/25000 [==============================] - 3s 131us/step - loss: 0.6399 - acc: 0.6476 - val_loss: 0.5057 - val_acc: 0.7713
Epoch 2/5
25000/25000 [==============================] - 2s 98us/step - loss: 0.4108 - acc: 0.8271 - val_loss: 0.3729 - val_acc: 0.8361
Epoch 3/5
25000/25000 [==============================] - 2s 98us/step - loss: 0.2898 - acc: 0.8860 - val_loss: 0.3646 - val_acc: 0.8388
Epoch 4/5
25000/25000 [==============================] - 2s 99us/step - loss: 0.2299 - acc: 0.9140 - val_loss: 0.4040 - val_acc: 0.8333
Epoch 5/5
25000/25000 [==============================] - 12s 475us/step
Test score: 0.4204186888217926
Test accuracy: 0.82604


In [79]:
a = np.array([[1,23415],[2, 3, 1], [1]])
a.shape

(3,)

In [80]:
b = sequence.pad_sequences(a,5)
b

array([[    0,     0,     0,     1, 23415],
       [    0,     0,     2,     3,     1],
       [    0,     0,     0,     0,     1]], dtype=int32)

In [81]:
b.shape

(3, 5)

In [93]:
a = np.array([[1,2, 2, 5, 7, 9, 1, 7, 9],[2, 3, 1, 5, 6, 5], [1, 4, 5]])
a.shape

(3,)

In [94]:
b = sequence.pad_sequences(a,9, padding='post')
print(b)
print(b.shape)

[[1 2 2 5 7 9 1 7 9]
 [2 3 1 5 6 5 0 0 0]
 [1 4 5 0 0 0 0 0 0]]
(3, 9)


In [95]:
b = b.reshape(3, 3, 3)
b

array([[[1, 2, 2],
        [5, 7, 9],
        [1, 7, 9]],

       [[2, 3, 1],
        [5, 6, 5],
        [0, 0, 0]],

       [[1, 4, 5],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)