In [23]:
import pandas as pd

In [24]:
df = pd.read_csv('up.csv')
df

Unnamed: 0  Unnamed: 1  Unnamed: 2
0       80.5460   283.89700     50.9832
1       80.0805   278.81300     51.7385
2       79.9859   264.15100     53.9335
3       79.5380   257.16100     54.7820
4       79.2844   245.89000     55.9122
..          ...         ...         ...
214     76.0001    10.43790     28.4667
215     75.6947     2.81893     31.1270
216     75.2740    -4.37299     33.1087
217     74.9959   -12.06750     35.3267
218     74.6437   -17.75180     35.5655

[219 rows x 3 columns]

In [25]:
import numpy as np

In [26]:
seq1 = pd.read_csv('./trajectory/up1.csv')
seq2 = pd.read_csv('./trajectory/up2.csv')

In [27]:
seq1 = np.array(seq1)
seq2 = np.array(seq2)
print(seq1.shape)
print(seq2.shape)

(35, 3)
(35, 3)


In [28]:
seq1 = np.append(seq1, seq2, axis=0)
np.set_printoptions(suppress=True)
seq1

array([[ 80.081    , 278.725    ,  51.5481   ],
       [ 79.809    , 268.847    ,  53.0291   ],
       [ 79.538    , 257.158    ,  54.7825   ],
       [ 79.2844   , 245.89     ,  55.9122   ],
       [ 78.8713   , 239.182    ,  56.0064   ],
       [ 78.4739   , 232.452    ,  55.5936   ],
       [ 78.259    , 218.466    ,  56.5888   ],
       [ 77.8914   , 208.481    ,  55.9948   ],
       [ 77.5442   , 200.509    ,  54.8337   ],
       [ 77.3829   , 189.691    ,  54.3085   ],
       [ 77.0679   , 180.679    ,  52.9485   ],
       [ 76.7701   , 171.867    ,  51.232    ],
       [ 76.648    , 162.067    ,  49.7529   ],
       [ 76.5374   , 152.249    ,  47.2838   ],
       [ 76.2805   , 144.166    ,  44.7854   ],
       [ 75.8809   , 138.212    ,  40.8821   ],
       [ 75.812    , 128.027    ,  38.242    ],
       [ 75.5966   , 120.273    ,  34.8816   ],
       [ 75.3965   , 112.388    ,  30.8262   ],
       [ 75.2178   , 103.768    ,  27.0571   ],
       [ 75.1927   ,  94.3475   ,  23.14

In [29]:
x_max = max(seq1[:,0])
x_min = min(seq1[:,0])
y_max = max(seq1[:,1])
y_min = min(seq1[:,1])
z_max = max(seq1[:,2])
z_min = min(seq1[:,2])
print(x_min, x_max, y_min, y_max, z_min, z_max)

66.4967 80.5073 -15.1893 278.767 2.5506599999999997 58.4673


In [30]:
seq1.shape
seq1 = seq1.reshape(2,35,3)
seq1

array([[[ 80.081    , 278.725    ,  51.5481   ],
        [ 79.809    , 268.847    ,  53.0291   ],
        [ 79.538    , 257.158    ,  54.7825   ],
        [ 79.2844   , 245.89     ,  55.9122   ],
        [ 78.8713   , 239.182    ,  56.0064   ],
        [ 78.4739   , 232.452    ,  55.5936   ],
        [ 78.259    , 218.466    ,  56.5888   ],
        [ 77.8914   , 208.481    ,  55.9948   ],
        [ 77.5442   , 200.509    ,  54.8337   ],
        [ 77.3829   , 189.691    ,  54.3085   ],
        [ 77.0679   , 180.679    ,  52.9485   ],
        [ 76.7701   , 171.867    ,  51.232    ],
        [ 76.648    , 162.067    ,  49.7529   ],
        [ 76.5374   , 152.249    ,  47.2838   ],
        [ 76.2805   , 144.166    ,  44.7854   ],
        [ 75.8809   , 138.212    ,  40.8821   ],
        [ 75.812    , 128.027    ,  38.242    ],
        [ 75.5966   , 120.273    ,  34.8816   ],
        [ 75.3965   , 112.388    ,  30.8262   ],
        [ 75.2178   , 103.768    ,  27.0571   ],
        [ 75.1927   

In [31]:
seq1.shape[0]

2

In [32]:
tmp = np.zeros((2,35,3))

In [33]:

for i in range(seq1.shape[0]):
    for j in range(seq1.shape[1]):
        tmp[i,j,0] = (seq1[i,j,0]-x_min)/(x_max-x_min)
        tmp[i,j,1] = (seq1[i,j,1]-y_min)/(y_max-y_min)
        tmp[i,j,2] = (seq1[i,j,2]-z_min)/(z_max-z_min)
        
tmp

array([[[0.96957304, 0.99985712, 0.87625866],
        [0.95015917, 0.96625349, 0.90274451],
        [0.93081667, 0.92648907, 0.93410191],
        [0.91271609, 0.88815685, 0.95430519],
        [0.88323127, 0.86533713, 0.95598984],
        [0.85486703, 0.84244257, 0.94860743],
        [0.83952864, 0.79486407, 0.96640535],
        [0.81329137, 0.76089643, 0.95578239],
        [0.78851013, 0.73377676, 0.93501755],
        [0.77699742, 0.69697537, 0.925625  ],
        [0.75451444, 0.66631775, 0.90130308],
        [0.7332591 , 0.6363405 , 0.8706056 ],
        [0.72454427, 0.60300221, 0.84415373],
        [0.71665025, 0.56960269, 0.79999692],
        [0.69831413, 0.54210541, 0.75531613],
        [0.66979287, 0.5218507 , 0.68551043],
        [0.66487517, 0.48720269, 0.63829551],
        [0.64950109, 0.46082462, 0.5781989 ],
        [0.63521905, 0.4340009 , 0.50567309],
        [0.62246442, 0.40467682, 0.43826739],
        [0.62067292, 0.37262954, 0.36822921],
        [0.60949567, 0.34523091, 0

In [34]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, RepeatVector, TimeDistributed

In [35]:
hidden_layer = 256
n_step = 35
features = 3

In [36]:
model = Sequential()
model.add(LSTM(hidden_layer, activation='relu', input_shape=(n_step, features)))
model.add(RepeatVector(n_step))
model.add(LSTM(hidden_layer, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(3)))

In [37]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 256)               266240    
_________________________________________________________________
repeat_vector_2 (RepeatVecto (None, 35, 256)           0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 35, 256)           525312    
_________________________________________________________________
time_distributed_2 (TimeDist (None, 35, 3)             771       
Total params: 792,323
Trainable params: 792,323
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])

In [44]:
model.fit(tmp, tmp, batch_size=2, epochs=300)

Epoch 1/300
2/2 [==============================] - 0s 26ms/step - loss: 1.4195e-04 - acc: 0.9571
Epoch 2/300
2/2 [==============================] - 0s 25ms/step - loss: 1.4126e-04 - acc: 0.9571
Epoch 3/300
2/2 [==============================] - 0s 25ms/step - loss: 1.4069e-04 - acc: 0.9571
Epoch 4/300
2/2 [==============================] - 0s 25ms/step - loss: 1.4044e-04 - acc: 0.9571
Epoch 5/300
2/2 [==============================] - 0s 25ms/step - loss: 1.4009e-04 - acc: 0.9571
Epoch 6/300
2/2 [==============================] - 0s 25ms/step - loss: 1.3924e-04 - acc: 0.9571
Epoch 7/300
2/2 [==============================] - 0s 27ms/step - loss: 1.3914e-04 - acc: 0.9571
Epoch 8/300
2/2 [==============================] - 0s 25ms/step - loss: 1.3858e-04 - acc: 0.9571
Epoch 9/300
2/2 [==============================] - 0s 27ms/step - loss: 1.3820e-04 - acc: 0.9571
Epoch 10/300
2/2 [==============================] - 0s 24ms/step - loss: 1.3767e-04 - acc: 0.9571
Epoch 11/300
2/2 [===========

Epoch 85/300
2/2 [==============================] - 0s 24ms/step - loss: 1.1039e-04 - acc: 0.9571
Epoch 86/300
2/2 [==============================] - 0s 23ms/step - loss: 1.1003e-04 - acc: 0.9571
Epoch 87/300
2/2 [==============================] - 0s 23ms/step - loss: 1.0971e-04 - acc: 0.9571
Epoch 88/300
2/2 [==============================] - 0s 23ms/step - loss: 1.0937e-04 - acc: 0.9571
Epoch 89/300
2/2 [==============================] - 0s 23ms/step - loss: 1.0903e-04 - acc: 0.9571
Epoch 90/300
2/2 [==============================] - 0s 24ms/step - loss: 1.0870e-04 - acc: 0.9571
Epoch 91/300
2/2 [==============================] - 0s 26ms/step - loss: 1.0836e-04 - acc: 0.9571
Epoch 92/300
2/2 [==============================] - 0s 23ms/step - loss: 1.0803e-04 - acc: 0.9571
Epoch 93/300
2/2 [==============================] - 0s 25ms/step - loss: 1.0768e-04 - acc: 0.9571
Epoch 94/300
2/2 [==============================] - 0s 24ms/step - loss: 1.0735e-04 - acc: 0.9571
Epoch 95/300
2/2 [==

Epoch 168/300
2/2 [==============================] - 0s 24ms/step - loss: 8.5317e-05 - acc: 0.9714
Epoch 169/300
2/2 [==============================] - 0s 23ms/step - loss: 8.5025e-05 - acc: 0.9714
Epoch 170/300
2/2 [==============================] - 0s 24ms/step - loss: 8.4741e-05 - acc: 0.9714
Epoch 171/300
2/2 [==============================] - 0s 23ms/step - loss: 8.4486e-05 - acc: 0.9714
Epoch 172/300
2/2 [==============================] - 0s 22ms/step - loss: 8.4182e-05 - acc: 0.9714
Epoch 173/300
2/2 [==============================] - 0s 25ms/step - loss: 8.3882e-05 - acc: 0.9714
Epoch 174/300
2/2 [==============================] - 0s 24ms/step - loss: 8.3603e-05 - acc: 0.9714
Epoch 175/300
2/2 [==============================] - 0s 25ms/step - loss: 8.3320e-05 - acc: 0.9714
Epoch 176/300
2/2 [==============================] - 0s 24ms/step - loss: 8.3042e-05 - acc: 0.9714
Epoch 177/300
2/2 [==============================] - 0s 24ms/step - loss: 8.2750e-05 - acc: 0.9714
Epoch 178/

Epoch 251/300
2/2 [==============================] - 0s 25ms/step - loss: 6.6722e-05 - acc: 0.9714
Epoch 252/300
2/2 [==============================] - 0s 25ms/step - loss: 6.6513e-05 - acc: 0.9714
Epoch 253/300
2/2 [==============================] - 0s 23ms/step - loss: 6.6319e-05 - acc: 0.9714
Epoch 254/300
2/2 [==============================] - 0s 25ms/step - loss: 6.6159e-05 - acc: 0.9714
Epoch 255/300
2/2 [==============================] - 0s 25ms/step - loss: 6.6003e-05 - acc: 0.9714
Epoch 256/300
2/2 [==============================] - 0s 23ms/step - loss: 6.5809e-05 - acc: 0.9714
Epoch 257/300
2/2 [==============================] - 0s 24ms/step - loss: 6.5590e-05 - acc: 0.9714
Epoch 258/300
2/2 [==============================] - 0s 23ms/step - loss: 6.5409e-05 - acc: 0.9714
Epoch 259/300
2/2 [==============================] - 0s 25ms/step - loss: 6.5233e-05 - acc: 0.9714
Epoch 260/300
2/2 [==============================] - 0s 24ms/step - loss: 6.5075e-05 - acc: 0.9714
Epoch 261/

In [45]:
yhat = model.predict(tmp)
yhat

array([[[0.97578317, 0.9910567 , 0.8744128 ],
        [0.95546156, 0.9710829 , 0.90272266],
        [0.93547094, 0.93219686, 0.9190139 ],
        [0.91236436, 0.8963928 , 0.93848175],
        [0.8886017 , 0.862756  , 0.9518139 ],
        [0.86333334, 0.82920325, 0.9573635 ],
        [0.8393257 , 0.794567  , 0.95692104],
        [0.8173861 , 0.7600616 , 0.95131254],
        [0.7976575 , 0.7262484 , 0.94096136],
        [0.7781739 , 0.693081  , 0.9249258 ],
        [0.75999016, 0.6618968 , 0.90374386],
        [0.7428411 , 0.63254106, 0.8763191 ],
        [0.72539496, 0.6037282 , 0.8419985 ],
        [0.7073461 , 0.575063  , 0.8006821 ],
        [0.6890193 , 0.5466912 , 0.75280905],
        [0.67153484, 0.51867115, 0.6999425 ],
        [0.656312  , 0.49090838, 0.642821  ],
        [0.6424111 , 0.462717  , 0.5808066 ],
        [0.63010067, 0.43434778, 0.51383305],
        [0.6201238 , 0.4065707 , 0.44188687],
        [0.6122562 , 0.37703183, 0.36378598],
        [0.60346836, 0.34954727, 0

In [46]:
pred = yhat
for i in range(yhat.shape[0]):
    for j in range(yhat.shape[1]):
        pred[i,j,0] = pred[i,j,0]*(x_max-x_min)+x_min
        pred[i,j,1] = pred[i,j,1]*(y_max-y_min)+y_min
        pred[i,j,2] = pred[i,j,2]*(z_max-z_min)+z_min
pred

array([[[ 80.16801  , 276.13806  ,  51.444885 ],
        [ 79.88329  , 270.26663  ,  53.027878 ],
        [ 79.60321  , 258.83585  ,  53.93883  ],
        [ 79.27947  , 248.31102  ,  55.027405 ],
        [ 78.94654  , 238.42326  ,  55.772892 ],
        [ 78.59252  , 228.56021  ,  56.08321  ],
        [ 78.25616  , 218.37868  ,  56.058468 ],
        [ 77.94877  , 208.2356   ,  55.74486  ],
        [ 77.67236  , 198.29599  ,  55.166058 ],
        [ 77.39938  , 188.54623  ,  54.2694   ],
        [ 77.144615 , 179.37944  ,  53.08498  ],
        [ 76.90435  , 170.75014  ,  51.55148  ],
        [ 76.65992  , 162.2804   ,  49.63239  ],
        [ 76.40704  , 153.8541   ,  47.322113 ],
        [ 76.150276 , 145.51402  ,  44.645214 ],
        [ 75.905304 , 137.27736  ,  41.689095 ],
        [ 75.692024 , 129.11632  ,  38.495052 ],
        [ 75.49727  , 120.82928  ,  35.027412 ],
        [ 75.32479  , 112.48997  ,  31.282478 ],
        [ 75.185005 , 104.32472  ,  27.25949  ],
        [ 75.074776 

In [47]:
seq1

array([[[ 80.081    , 278.725    ,  51.5481   ],
        [ 79.809    , 268.847    ,  53.0291   ],
        [ 79.538    , 257.158    ,  54.7825   ],
        [ 79.2844   , 245.89     ,  55.9122   ],
        [ 78.8713   , 239.182    ,  56.0064   ],
        [ 78.4739   , 232.452    ,  55.5936   ],
        [ 78.259    , 218.466    ,  56.5888   ],
        [ 77.8914   , 208.481    ,  55.9948   ],
        [ 77.5442   , 200.509    ,  54.8337   ],
        [ 77.3829   , 189.691    ,  54.3085   ],
        [ 77.0679   , 180.679    ,  52.9485   ],
        [ 76.7701   , 171.867    ,  51.232    ],
        [ 76.648    , 162.067    ,  49.7529   ],
        [ 76.5374   , 152.249    ,  47.2838   ],
        [ 76.2805   , 144.166    ,  44.7854   ],
        [ 75.8809   , 138.212    ,  40.8821   ],
        [ 75.812    , 128.027    ,  38.242    ],
        [ 75.5966   , 120.273    ,  34.8816   ],
        [ 75.3965   , 112.388    ,  30.8262   ],
        [ 75.2178   , 103.768    ,  27.0571   ],
        [ 75.1927   

In [48]:
error = np.zeros((seq1.shape[0], seq1.shape[1], seq1.shape[2]))
for i in range(error.shape[0]):
    for j in range(error.shape[1]):
        for k in range(error.shape[2]):
            error[i,j,k] = seq1[i,j,k]-pred[i,j,k]
error

array([[[-0.0870069 ,  2.58693848,  0.10321475],
        [-0.07429315, -1.41963208,  0.00122219],
        [-0.06521045, -1.67784595,  0.84366867],
        [ 0.00492765, -2.4210199 ,  0.88479521],
        [-0.07524083,  0.75873645,  0.233508  ],
        [-0.11862167,  3.89178882, -0.48960999],
        [ 0.00284308,  0.08732263,  0.53033214],
        [-0.05736862,  0.2454043 ,  0.2499384 ],
        [-0.12816328,  2.21301001, -0.33235759],
        [-0.01648354,  1.14476587,  0.03909845],
        [-0.07671517,  1.29955969, -0.13648001],
        [-0.13425028,  1.11686267, -0.31947934],
        [-0.01191974, -0.21339551,  0.12051093],
        [ 0.13035654, -1.60509546, -0.03831304],
        [ 0.13022382, -1.34802283,  0.14018592],
        [-0.02440396,  0.93464099, -0.80699454],
        [ 0.11997577, -1.08931775, -0.25305234],
        [ 0.09933132, -0.55627704, -0.14581241],
        [ 0.07170905, -0.10196735, -0.45627833],
        [ 0.03279481, -0.55672229, -0.20238906],
        [ 0.1179243 