In [294]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense, RepeatVector, TimeDistributed
import pandas as pd

In [295]:
traj1 = pd.read_csv('traj11.csv')
print(traj1)
print(traj1.shape)

    Unnamed: 0  Unnamed: 1  Unnamed: 2
0      80.0810  278.725000    51.54810
1      79.8090  268.847000    53.02910
2      79.5380  257.158000    54.78250
3      79.2844  245.890000    55.91220
4      78.8713  239.182000    56.00640
5      78.4739  232.452000    55.59360
6      78.2590  218.466000    56.58880
7      77.8914  208.481000    55.99480
8      77.5442  200.509000    54.83370
9      77.3829  189.691000    54.30850
10     77.0679  180.679000    52.94850
11     76.7701  171.867000    51.23200
12     76.6480  162.067000    49.75290
13     76.5374  152.249000    47.28380
14     76.2805  144.166000    44.78540
15     75.8809  138.212000    40.88210
16     75.8120  128.027000    38.24200
17     75.5966  120.273000    34.88160
18     75.3965  112.388000    30.82620
19     75.2178  103.768000    27.05710
20     75.1927   94.347500    23.14080
21     75.0361   86.293500    19.32310
22     74.8874   78.757300    14.24170
23     74.2345   73.254600     7.71324
24     74.4951   64.70060

In [296]:
traj2 = pd.read_csv('traj22.csv')
print(traj2)
print(traj2.shape)

    Unnamed: 0  Unnamed: 1  Unnamed: 2
0      80.5073  278.767000    51.75110
1      80.0317  271.437000    53.04240
2      79.5616  261.925000    54.45600
3      79.1246  254.925000    55.11250
4      79.0613  239.576000    56.86800
5      78.4545  227.110000    57.68750
6      78.4272  215.415000    58.46730
7      77.8861  207.261000    57.38790
8      77.5370  198.303000    57.71050
9      77.2104  187.726000    57.25210
10     76.5766  179.795000    54.54560
11     76.4611  168.345000    53.50290
12     75.7186  161.460000    51.70510
13     75.3215  153.110000    49.31900
14     74.9557  143.856000    47.20570
15     74.6011  135.734000    44.02310
16     74.2918  125.819000    41.59060
17     73.8550  117.100000    38.41110
18     73.2939  109.566000    34.85770
19     72.8906  102.092000    30.99280
20     72.5106   94.534300    26.61690
21     72.2142   84.696300    23.13340
22     71.7601   77.246300    18.20840
23     71.3283   70.044700    13.49500
24     70.7819   63.44260

In [297]:
n_step = len(traj1)
print(n_step)

35


In [298]:
samples = 1 # batch_size
features = 3 # n_input
hidden_layer = 256
epochs = 500

In [299]:
seq1 = np.array(traj1)
seq2 = np.array(traj2)
seq1

array([[ 80.081   , 278.725   ,  51.5481  ],
       [ 79.809   , 268.847   ,  53.0291  ],
       [ 79.538   , 257.158   ,  54.7825  ],
       [ 79.2844  , 245.89    ,  55.9122  ],
       [ 78.8713  , 239.182   ,  56.0064  ],
       [ 78.4739  , 232.452   ,  55.5936  ],
       [ 78.259   , 218.466   ,  56.5888  ],
       [ 77.8914  , 208.481   ,  55.9948  ],
       [ 77.5442  , 200.509   ,  54.8337  ],
       [ 77.3829  , 189.691   ,  54.3085  ],
       [ 77.0679  , 180.679   ,  52.9485  ],
       [ 76.7701  , 171.867   ,  51.232   ],
       [ 76.648   , 162.067   ,  49.7529  ],
       [ 76.5374  , 152.249   ,  47.2838  ],
       [ 76.2805  , 144.166   ,  44.7854  ],
       [ 75.8809  , 138.212   ,  40.8821  ],
       [ 75.812   , 128.027   ,  38.242   ],
       [ 75.5966  , 120.273   ,  34.8816  ],
       [ 75.3965  , 112.388   ,  30.8262  ],
       [ 75.2178  , 103.768   ,  27.0571  ],
       [ 75.1927  ,  94.3475  ,  23.1408  ],
       [ 75.0361  ,  86.2935  ,  19.3231  ],
       [ 7

In [300]:
seq1 = seq1.reshape(samples, n_step, features)
max_x = np.max(seq1[:,:,0])
min_x = np.min(seq1[:,:,0])
max_y = np.max(seq1[:,:,1])
min_y = np.min(seq1[:,:,1])
max_z = np.max(seq1[:,:,2])
min_z = np.min(seq1[:,:,2])
print(max_x, min_x, max_y, min_y, max_z, min_z)

80.081 72.6624 278.725 -14.8458 56.5888 2.5506599999999997


In [301]:
tmp_x = []
tmp_y = []
tmp_z = []
for i in seq1[:,:,0]:
    tmp_x.append((i-min_x)/(max_x-min_x))
tmp_x = np.array(tmp_x)
#print(tmp_x)

for i in seq1[:,:,1]:
    tmp_y.append((i-min_y)/(max_y-min_y))
tmp_y = np.array(tmp_y)

for i in seq1[:,:,2]:
    tmp_z.append((i-min_z)/(max_z-min_z))
tmp_z = np.array(tmp_z)

for i in range(35):
    seq1[:,i,0] = tmp_x[0,i]
    seq1[:,i,1] = tmp_y[0,i]
    seq1[:,i,2] = tmp_z[0,i]
#for i in range(len(tmp_x)):
    #seq1[:,i,0] = tmp_x[i,0]
print(seq1)
#print(seq1[:,2,0])

[[[1.         1.         0.90671959]
  [0.9633354  0.96635224 0.93412616]
  [0.9268056  0.92653561 0.96657361]
  [0.89262125 0.88815305 0.98747921]
  [0.83693689 0.86530336 0.98922243]
  [0.78336883 0.84237874 0.98158338]
  [0.7544011  0.79473776 1.        ]
  [0.70484997 0.76072552 0.98900776]
  [0.65804869 0.73357023 0.96752109]
  [0.63630604 0.69672052 0.95780203]
  [0.5938452  0.66602264 0.93263462]
  [0.55370285 0.63600603 0.90087002]
  [0.53724422 0.60262397 0.87349861]
  [0.52233575 0.56918059 0.8278068 ]
  [0.48770658 0.54164719 0.78157279]
  [0.43384196 0.52136589 0.70934048]
  [0.4245545  0.48667238 0.66048424]
  [0.39551937 0.46025967 0.59829854]
  [0.36854663 0.43340073 0.52325154]
  [0.34445852 0.40403814 0.45350266]
  [0.34107514 0.37194878 0.38102977]
  [0.31996603 0.34451417 0.31038152]
  [0.29992182 0.31884336 0.21634793]
  [0.2119133  0.30009933 0.09553586]
  [0.24704122 0.27096155 0.01916572]
  [0.23490955 0.24245054 0.        ]
  [0.19668131 0.21376377 0.09780222]
 

In [302]:
model = Sequential()
model.add(LSTM(hidden_layer, activation='relu', input_shape=(n_step, features)))
model.add(RepeatVector(n_step))
model.add(LSTM(hidden_layer, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(3)))

In [303]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_37 (LSTM)               (None, 256)               266240    
_________________________________________________________________
repeat_vector_15 (RepeatVect (None, 35, 256)           0         
_________________________________________________________________
lstm_38 (LSTM)               (None, 35, 256)           525312    
_________________________________________________________________
time_distributed_17 (TimeDis (None, 35, 3)             771       
Total params: 792,323
Trainable params: 792,323
Non-trainable params: 0
_________________________________________________________________


In [304]:
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
model.fit(seq1, seq1, epochs=epochs, verbose=2)

Epoch 1/500
 - 2s - loss: 0.3545 - acc: 0.0286
Epoch 2/500
 - 0s - loss: 0.3405 - acc: 0.7429
Epoch 3/500
 - 0s - loss: 0.3269 - acc: 0.7429
Epoch 4/500
 - 0s - loss: 0.3121 - acc: 0.7429
Epoch 5/500
 - 0s - loss: 0.2939 - acc: 0.7429
Epoch 6/500
 - 0s - loss: 0.2700 - acc: 0.7429
Epoch 7/500
 - 0s - loss: 0.2367 - acc: 0.7429
Epoch 8/500
 - 0s - loss: 0.1927 - acc: 0.7429
Epoch 9/500
 - 0s - loss: 0.2344 - acc: 0.7429
Epoch 10/500
 - 0s - loss: 0.1717 - acc: 0.7429
Epoch 11/500
 - 0s - loss: 0.1685 - acc: 0.7429
Epoch 12/500
 - 0s - loss: 0.1734 - acc: 0.7429
Epoch 13/500
 - 0s - loss: 0.1760 - acc: 0.7429
Epoch 14/500
 - 0s - loss: 0.1753 - acc: 0.7429
Epoch 15/500
 - 0s - loss: 0.1719 - acc: 0.7429
Epoch 16/500
 - 0s - loss: 0.1668 - acc: 0.6857
Epoch 17/500
 - 0s - loss: 0.1608 - acc: 0.4571
Epoch 18/500
 - 0s - loss: 0.1550 - acc: 0.5143
Epoch 19/500
 - 0s - loss: 0.1501 - acc: 0.7429
Epoch 20/500
 - 0s - loss: 0.1462 - acc: 0.7429
Epoch 21/500
 - 0s - loss: 0.1428 - acc: 0.7429
E

Epoch 171/500
 - 0s - loss: 0.0120 - acc: 0.7429
Epoch 172/500
 - 0s - loss: 0.0122 - acc: 0.7429
Epoch 173/500
 - 0s - loss: 0.0123 - acc: 0.7429
Epoch 174/500
 - 0s - loss: 0.0120 - acc: 0.7429
Epoch 175/500
 - 0s - loss: 0.0117 - acc: 0.7429
Epoch 176/500
 - 0s - loss: 0.0116 - acc: 0.7429
Epoch 177/500
 - 0s - loss: 0.0112 - acc: 0.7714
Epoch 178/500
 - 0s - loss: 0.0112 - acc: 0.7714
Epoch 179/500
 - 0s - loss: 0.0114 - acc: 0.7714
Epoch 180/500
 - 0s - loss: 0.0112 - acc: 0.7714
Epoch 181/500
 - 0s - loss: 0.0112 - acc: 0.7714
Epoch 182/500
 - 0s - loss: 0.0109 - acc: 0.7714
Epoch 183/500
 - 0s - loss: 0.0105 - acc: 0.7429
Epoch 184/500
 - 0s - loss: 0.0103 - acc: 0.7429
Epoch 185/500
 - 0s - loss: 0.0101 - acc: 0.7429
Epoch 186/500
 - 0s - loss: 0.0100 - acc: 0.7429
Epoch 187/500
 - 0s - loss: 0.0100 - acc: 0.7143
Epoch 188/500
 - 0s - loss: 0.0098 - acc: 0.7143
Epoch 189/500
 - 0s - loss: 0.0097 - acc: 0.7429
Epoch 190/500
 - 0s - loss: 0.0095 - acc: 0.7429
Epoch 191/500
 - 0s 

 - 0s - loss: 0.0012 - acc: 0.9429
Epoch 339/500
 - 0s - loss: 9.5456e-04 - acc: 0.8857
Epoch 340/500
 - 0s - loss: 0.0011 - acc: 0.8857
Epoch 341/500
 - 0s - loss: 0.0010 - acc: 0.8857
Epoch 342/500
 - 0s - loss: 0.0010 - acc: 0.8857
Epoch 343/500
 - 0s - loss: 0.0011 - acc: 0.8857
Epoch 344/500
 - 0s - loss: 8.6949e-04 - acc: 0.8857
Epoch 345/500
 - 0s - loss: 9.5837e-04 - acc: 0.9143
Epoch 346/500
 - 0s - loss: 8.3992e-04 - acc: 0.8571
Epoch 347/500
 - 0s - loss: 8.4827e-04 - acc: 0.8571
Epoch 348/500
 - 0s - loss: 8.7632e-04 - acc: 0.9143
Epoch 349/500
 - 0s - loss: 7.5159e-04 - acc: 0.9429
Epoch 350/500
 - 0s - loss: 7.9139e-04 - acc: 0.8857
Epoch 351/500
 - 0s - loss: 7.7988e-04 - acc: 0.9714
Epoch 352/500
 - 0s - loss: 7.1265e-04 - acc: 0.9429
Epoch 353/500
 - 0s - loss: 7.6518e-04 - acc: 0.9143
Epoch 354/500
 - 0s - loss: 7.2285e-04 - acc: 0.9429
Epoch 355/500
 - 0s - loss: 7.0322e-04 - acc: 0.9429
Epoch 356/500
 - 0s - loss: 7.2041e-04 - acc: 0.9429
Epoch 357/500
 - 0s - loss:

Epoch 494/500
 - 0s - loss: 1.5210e-04 - acc: 1.0000
Epoch 495/500
 - 0s - loss: 1.5542e-04 - acc: 0.9714
Epoch 496/500
 - 0s - loss: 1.6191e-04 - acc: 1.0000
Epoch 497/500
 - 0s - loss: 1.7020e-04 - acc: 0.9429
Epoch 498/500
 - 0s - loss: 1.8258e-04 - acc: 1.0000
Epoch 499/500
 - 0s - loss: 1.9736e-04 - acc: 0.9429
Epoch 500/500
 - 0s - loss: 2.0352e-04 - acc: 1.0000


In [305]:
seq2 = seq2.reshape(samples, n_step, features)
yhat = model.predict(seq1, verbose=0)
print(yhat)
print(seq1)

[[[ 1.004265    1.0025865   0.90332717]
  [ 0.9551469   0.954815    0.9393956 ]
  [ 0.936165    0.9378138   0.9727536 ]
  [ 0.88487     0.8943185   0.9771603 ]
  [ 0.8355143   0.85930276  0.983883  ]
  [ 0.7874446   0.8260801   0.9859396 ]
  [ 0.7440346   0.7938316   0.9847095 ]
  [ 0.7037892   0.7617144   0.9783092 ]
  [ 0.6661971   0.7297125   0.9662514 ]
  [ 0.6311293   0.6979078   0.94858086]
  [ 0.59743065  0.666001    0.92454237]
  [ 0.5645591   0.63413745  0.8937564 ]
  [ 0.5321128   0.60242283  0.8558102 ]
  [ 0.5012355   0.57110864  0.81216145]
  [ 0.47203687  0.5402817   0.7635469 ]
  [ 0.4443321   0.5098112   0.70947295]
  [ 0.41811696  0.48004174  0.64950585]
  [ 0.39340466  0.4512576   0.5835404 ]
  [ 0.37014803  0.42357266  0.5117015 ]
  [ 0.3482813   0.3969736   0.43434003]
  [ 0.3275829   0.3711521   0.35147136]
  [ 0.3067092   0.34383124  0.2615813 ]
  [ 0.2834942   0.31540102  0.1690185 ]
  [ 0.2589112   0.2890876   0.08984619]
  [ 0.23487046  0.26367655  0.05127198]


In [306]:
for i in range(35):
    yhat[:,i,0] = yhat[:,i,0]*(max_x-min_x)+min_x
    yhat[:,i,1] = yhat[:,i,1]*(max_y-min_y)+min_y
    yhat[:,i,2] = yhat[:,i,2]*(max_z-min_z)+min_z
print(yhat)

[[[ 80.11264   279.4843     51.364777 ]
  [ 79.74825   265.46       53.31385  ]
  [ 79.60743   260.46896    55.11645  ]
  [ 79.2269    247.70001    55.354584 ]
  [ 78.86075   237.42041    55.71787  ]
  [ 78.504135  227.66719    55.829002 ]
  [ 78.1821    218.19998    55.762527 ]
  [ 77.88353   208.77132    55.416668 ]
  [ 77.60465   199.37648    54.765087 ]
  [ 77.3445    190.03957    53.810204 ]
  [ 77.0945    180.67265    52.511208 ]
  [ 76.85064   171.31845    50.84759  ]
  [ 76.60993   162.00797    48.79705  ]
  [ 76.38087   152.81503    46.43835  ]
  [ 76.16425   143.76514    43.811314 ]
  [ 75.958725  134.8199     40.88926  ]
  [ 75.764244  126.08044    37.648746 ]
  [ 75.58091   117.63024    34.084095 ]
  [ 75.40838   109.50276    30.202057 ]
  [ 75.24616   101.69406    26.021585 ]
  [ 75.092606   94.11362    21.543518 ]
  [ 74.93775    86.09301    16.686026 ]
  [ 74.765526   77.74673    11.684106 ]
  [ 74.58316    70.02187     7.405781 ]
  [ 74.40481    62.561935    5.3213024]


In [307]:
seq_act = pd.read_csv('traj11.csv')
seq_act = np.array(seq_act)
seq_act = seq_act.reshape(samples, n_step, features)
print(seq_act)
print(seq_act.shape)

[[[ 80.081    278.725     51.5481  ]
  [ 79.809    268.847     53.0291  ]
  [ 79.538    257.158     54.7825  ]
  [ 79.2844   245.89      55.9122  ]
  [ 78.8713   239.182     56.0064  ]
  [ 78.4739   232.452     55.5936  ]
  [ 78.259    218.466     56.5888  ]
  [ 77.8914   208.481     55.9948  ]
  [ 77.5442   200.509     54.8337  ]
  [ 77.3829   189.691     54.3085  ]
  [ 77.0679   180.679     52.9485  ]
  [ 76.7701   171.867     51.232   ]
  [ 76.648    162.067     49.7529  ]
  [ 76.5374   152.249     47.2838  ]
  [ 76.2805   144.166     44.7854  ]
  [ 75.8809   138.212     40.8821  ]
  [ 75.812    128.027     38.242   ]
  [ 75.5966   120.273     34.8816  ]
  [ 75.3965   112.388     30.8262  ]
  [ 75.2178   103.768     27.0571  ]
  [ 75.1927    94.3475    23.1408  ]
  [ 75.0361    86.2935    19.3231  ]
  [ 74.8874    78.7573    14.2417  ]
  [ 74.2345    73.2546     7.71324 ]
  [ 74.4951    64.7006     3.58634 ]
  [ 74.4051    56.3306     2.55066 ]
  [ 74.1215    47.909      7.83571 ]
 

In [308]:
error = np.zeros((1,35,3))
#print(error)
for i in range(35):
    error[:,i,0] = seq_act[:,i,0]-yhat[:,i,0]
    error[:,i,1] = seq_act[:,i,1]-yhat[:,i,1]
    error[:,i,2] = seq_act[:,i,2]-yhat[:,i,2]
np.set_printoptions(suppress=True)
print(error)

[[[-0.03164038 -0.75931396  0.18332339]
  [ 0.06074713  3.38700854 -0.2847504 ]
  [-0.0694295  -3.31096362 -0.33395126]
  [ 0.05750181 -1.81001221  0.55761626]
  [ 0.01055171  1.76158984  0.2885312 ]
  [-0.03023513  4.78480945 -0.23540238]
  [ 0.07690161  0.26601831  0.82627253]
  [ 0.00787034 -0.29031653  0.57813206]
  [-0.0604524   1.1325199   0.06861287]
  [ 0.03840232 -0.34856604  0.49829645]
  [-0.02659768  0.0063468   0.43729242]
  [-0.08053934  0.54854907  0.3844086 ]
  [ 0.03806805  0.05903491  0.95584952]
  [ 0.156533   -0.56603296  0.84544932]
  [ 0.11624677  0.40086328  0.97408637]
  [-0.07782498  3.39209949 -0.00715934]
  [ 0.04775592  1.94656329  0.59325351]
  [ 0.01569027  2.64275861  0.797505  ]
  [-0.0118786   2.88523816  0.62414312]
  [-0.02836241  2.07393872  1.03551454]
  [ 0.10009441  0.23388306  1.59728193]
  [ 0.09834823  0.20049005  2.63707438]
  [ 0.12187418  1.01057301  2.55759413]
  [-0.3486604   3.23272653  0.30745921]
  [ 0.09029196  2.13866458 -1.73496241]


In [309]:
max_x2 = np.max(seq2[:,:,0])
min_x2 = np.min(seq2[:,:,0])
max_y2 = np.max(seq2[:,:,1])
min_y2 = np.min(seq2[:,:,1])
max_z2 = np.max(seq2[:,:,2])
min_z2 = np.min(seq2[:,:,2])
print(max_x2, min_x2, max_y2, min_y2, max_z2, min_z2)

80.5073 66.4967 278.767 -15.1893 58.4673 2.66722


In [310]:
tmp_x = []
tmp_y = []
tmp_z = []
for i in seq2[:,:,0]:
    tmp_x.append((i-min_x2)/(max_x2-min_x2))
tmp_x = np.array(tmp_x)
#print(tmp_x)

for i in seq2[:,:,1]:
    tmp_y.append((i-min_y2)/(max_y2-min_y2))
tmp_y = np.array(tmp_y)

for i in seq2[:,:,2]:
    tmp_z.append((i-min_z2)/(max_z2-min_z2))
tmp_z = np.array(tmp_z)

for i in range(35):
    seq2[:,i,0] = tmp_x[0,i]
    seq2[:,i,1] = tmp_y[0,i]
    seq2[:,i,2] = tmp_z[0,i]
    
print(seq2)

[[[1.         1.         0.87963817]
  [0.96605427 0.97506432 0.90277971]
  [0.93250111 0.94270577 0.92811301]
  [0.90131044 0.91889271 0.93987822]
  [0.89679243 0.86667746 0.97133875]
  [0.85348236 0.8242698  0.98602511]
  [0.85153384 0.78448497 1.        ]
  [0.81291308 0.75674616 0.98065594]
  [0.78799623 0.72627224 0.9864373 ]
  [0.76468531 0.6902907  0.97822225]
  [0.71944813 0.6633105  0.92971874]
  [0.71120437 0.62435913 0.91103239]
  [0.65820878 0.60093728 0.87881379]
  [0.62986596 0.5725317  0.83605221]
  [0.60375716 0.54105083 0.7981795 ]
  [0.57844775 0.51342087 0.74114374]
  [0.5563716  0.47969137 0.69755061]
  [0.52519521 0.4500305  0.64057041]
  [0.48514696 0.42440084 0.5768895 ]
  [0.45636161 0.39897529 0.50762615]
  [0.42923929 0.37326501 0.42920512]
  [0.40808388 0.33979745 0.36677689]
  [0.3756727  0.31445354 0.27851537]
  [0.34485318 0.28995466 0.19404596]
  [0.30585414 0.2674952  0.09747871]
  [0.28693989 0.24253945 0.        ]
  [0.2541076  0.21339124 0.01973689]
 

In [311]:
yhat2 = model.predict(seq2, verbose=0)
print(yhat2)
print(seq2)

[[[ 0.98767155  0.98516613  0.8887216 ]
  [ 0.94515383  0.9446887   0.9290848 ]
  [ 0.92650145  0.9281383   0.9615574 ]
  [ 0.8762475   0.88570064  0.9654223 ]
  [ 0.82751685  0.851106    0.9709982 ]
  [ 0.78008115  0.81824416  0.9719287 ]
  [ 0.73721373  0.7863589   0.96957153]
  [ 0.6974832   0.75466263  0.9621281 ]
  [ 0.6605129   0.7231862   0.9492375 ]
  [ 0.62600774  0.69192487  0.93082607]
  [ 0.5928825   0.66063124  0.9062101 ]
  [ 0.56060195  0.6294351   0.8750372 ]
  [ 0.5287744   0.5984345   0.83694124]
  [ 0.49866945  0.5678553   0.793529  ]
  [ 0.4701709   0.5378041   0.74536365]
  [ 0.44316742  0.5081535   0.6921276 ]
  [ 0.41762152  0.47919762  0.63343835]
  [ 0.393539    0.45119882  0.5692489 ]
  [ 0.3708674   0.42425275  0.49973395]
  [ 0.34953657  0.39833307  0.42528236]
  [ 0.32919708  0.3727706   0.34562182]
  [ 0.30850244  0.3458705   0.2599686 ]
  [ 0.28560534  0.31782556  0.17269395]
  [ 0.26104906  0.29166877  0.09788483]
  [ 0.23714422  0.2665987   0.06223411]


In [312]:
for i in range(35):
    yhat2[:,i,0] = yhat2[:,i,0]*(max_x2-min_x2)+min_x2
    yhat2[:,i,1] = yhat2[:,i,1]*(max_y2-min_y2)+min_y2
    yhat2[:,i,2] = yhat2[:,i,2]*(max_z2-min_z2)+min_z2
print(yhat2)

[[[ 80.334564   274.4065      52.257957  ]
  [ 79.73887    262.50787     54.510227  ]
  [ 79.47754    257.6428      56.3222    ]
  [ 78.77345    245.16797     56.53786   ]
  [ 78.090706   234.99867     56.849     ]
  [ 77.4261     225.33873     56.90092   ]
  [ 76.8255     215.96585     56.76939   ]
  [ 76.26885    206.64853     56.354046  ]
  [ 75.75088    197.39584     55.63475   ]
  [ 75.26744    188.20638     54.60739   ]
  [ 74.80334    179.00742     53.233818  ]
  [ 74.35107    169.83711     51.494366  ]
  [ 73.90514    160.72429     49.36861   ]
  [ 73.48335    151.73534     46.9462    ]
  [ 73.084076   142.90161     44.25857   ]
  [ 72.705734   134.18562     41.287994  ]
  [ 72.347824   125.67386     38.01313   ]
  [ 72.010414   117.443436    34.431355  ]
  [ 71.69277    109.52247     30.552414  ]
  [ 71.39391    101.90321     26.39801   ]
  [ 71.10895     94.38897     21.952946  ]
  [ 70.819       86.48151     17.173489  ]
  [ 70.4982      78.237526    12.303556  ]
  [ 70.1541

In [313]:
seq_act2 = pd.read_csv('traj22.csv')
seq_act2 = np.array(seq_act2)
seq_act2 = seq_act2.reshape(samples, n_step, features)
print(seq_act2)
print(seq_act2.shape)

[[[ 80.5073    278.767      51.7511   ]
  [ 80.0317    271.437      53.0424   ]
  [ 79.5616    261.925      54.456    ]
  [ 79.1246    254.925      55.1125   ]
  [ 79.0613    239.576      56.868    ]
  [ 78.4545    227.11       57.6875   ]
  [ 78.4272    215.415      58.4673   ]
  [ 77.8861    207.261      57.3879   ]
  [ 77.537     198.303      57.7105   ]
  [ 77.2104    187.726      57.2521   ]
  [ 76.5766    179.795      54.5456   ]
  [ 76.4611    168.345      53.5029   ]
  [ 75.7186    161.46       51.7051   ]
  [ 75.3215    153.11       49.319    ]
  [ 74.9557    143.856      47.2057   ]
  [ 74.6011    135.734      44.0231   ]
  [ 74.2918    125.819      41.5906   ]
  [ 73.855     117.1        38.4111   ]
  [ 73.2939    109.566      34.8577   ]
  [ 72.8906    102.092      30.9928   ]
  [ 72.5106     94.5343     26.6169   ]
  [ 72.2142     84.6963     23.1334   ]
  [ 71.7601     77.2463     18.2084   ]
  [ 71.3283     70.0447     13.495    ]
  [ 70.7819     63.4426      8.10654  ]


In [315]:
print(yhat2)

[[[ 80.334564   274.4065      52.257957  ]
  [ 79.73887    262.50787     54.510227  ]
  [ 79.47754    257.6428      56.3222    ]
  [ 78.77345    245.16797     56.53786   ]
  [ 78.090706   234.99867     56.849     ]
  [ 77.4261     225.33873     56.90092   ]
  [ 76.8255     215.96585     56.76939   ]
  [ 76.26885    206.64853     56.354046  ]
  [ 75.75088    197.39584     55.63475   ]
  [ 75.26744    188.20638     54.60739   ]
  [ 74.80334    179.00742     53.233818  ]
  [ 74.35107    169.83711     51.494366  ]
  [ 73.90514    160.72429     49.36861   ]
  [ 73.48335    151.73534     46.9462    ]
  [ 73.084076   142.90161     44.25857   ]
  [ 72.705734   134.18562     41.287994  ]
  [ 72.347824   125.67386     38.01313   ]
  [ 72.010414   117.443436    34.431355  ]
  [ 71.69277    109.52247     30.552414  ]
  [ 71.39391    101.90321     26.39801   ]
  [ 71.10895     94.38897     21.952946  ]
  [ 70.819       86.48151     17.173489  ]
  [ 70.4982      78.237526    12.303556  ]
  [ 70.1541

In [314]:
error2 = np.zeros((1,35,3))
#print(error)
for i in range(35):
    error2[:,i,0] = seq_act2[:,i,0]-yhat2[:,i,0]
    error2[:,i,1] = seq_act2[:,i,1]-yhat2[:,i,1]
    error2[:,i,2] = seq_act2[:,i,2]-yhat2[:,i,2]
#np.set_printoptions(suppress=True)
print(error)
print(error2)

[[[-0.03164038 -0.75931396  0.18332339]
  [ 0.06074713  3.38700854 -0.2847504 ]
  [-0.0694295  -3.31096362 -0.33395126]
  [ 0.05750181 -1.81001221  0.55761626]
  [ 0.01055171  1.76158984  0.2885312 ]
  [-0.03023513  4.78480945 -0.23540238]
  [ 0.07690161  0.26601831  0.82627253]
  [ 0.00787034 -0.29031653  0.57813206]
  [-0.0604524   1.1325199   0.06861287]
  [ 0.03840232 -0.34856604  0.49829645]
  [-0.02659768  0.0063468   0.43729242]
  [-0.08053934  0.54854907  0.3844086 ]
  [ 0.03806805  0.05903491  0.95584952]
  [ 0.156533   -0.56603296  0.84544932]
  [ 0.11624677  0.40086328  0.97408637]
  [-0.07782498  3.39209949 -0.00715934]
  [ 0.04775592  1.94656329  0.59325351]
  [ 0.01569027  2.64275861  0.797505  ]
  [-0.0118786   2.88523816  0.62414312]
  [-0.02836241  2.07393872  1.03551454]
  [ 0.10009441  0.23388306  1.59728193]
  [ 0.09834823  0.20049005  2.63707438]
  [ 0.12187418  1.01057301  2.55759413]
  [-0.3486604   3.23272653  0.30745921]
  [ 0.09029196  2.13866458 -1.73496241]
