In [28]:
import numpy as np
import pandas as pd

In [29]:
traj = pd.read_csv('/home/lab606a/Documents/datasets/dataset_20200225.csv')
traj = traj.fillna(0)

In [30]:
traj = np.array(traj)
a = traj[0, :]
print(a)

[  1.      108.643   304.824    42.4588  109.714   291.945    45.2562
 110.357   281.201    47.1818  110.843   272.255    48.5718  111.769
 257.836    50.0968  112.027   247.682    50.9953  112.561   235.979
  51.2664  112.607   224.858    51.9736  112.959   212.587    51.2097
 113.022   204.526    50.4888  112.627   192.513    50.1693  112.808
 183.724    47.5524  112.288   171.345    46.8534  112.233   162.69
  43.4192  111.337   152.24     41.2016  111.453   142.327    37.5963
 110.868   134.702    34.5887  110.022   123.729    32.5556  109.63
 115.57     26.7696  108.584   104.427    24.0688  107.945    96.8253
  17.2024  106.826    86.577    14.6333  106.149    78.465     7.0065
 104.992    73.8841    2.82648 103.663    63.1727    5.07401 102.3
  59.0714    9.60417 100.619    50.7707   14.7243   99.314    46.2701
  18.3093   97.7961   41.8541   21.4989   96.0541   33.8609   25.6685
  94.4366   29.7369   27.9363   92.7192   21.8017   31.4817   90.9287
  18.1181   32.4892   89.2632 

In [31]:
len(a)

145

In [32]:
def split_seq(seq, n_step_in, n_step_out):
    X, Y = list(), list()
    for i in range(len(seq)):
        # find the end of this pattern
        end_ix = i + n_step_in
        out_end_ix = end_ix + n_step_out - 1
        # check if we are beyond the dataset
        if out_end_ix > len(seq):
            break
        # gather input and output parts of pattern
        seq_x, seq_y = seq[i:end_ix, :-1], seq[end_ix-1:out_end_ix, -1]
        X.append(seq_x)
        Y.append(seq_y)
    return np.array(X), np.array(Y)

In [33]:
#a = a.reshape(len(a), 1)
#x ,y = split_seq(a, 5, 5)

In [35]:
a = a[1:]
a

array([108.643  , 304.824  ,  42.4588 , 109.714  , 291.945  ,  45.2562 ,
       110.357  , 281.201  ,  47.1818 , 110.843  , 272.255  ,  48.5718 ,
       111.769  , 257.836  ,  50.0968 , 112.027  , 247.682  ,  50.9953 ,
       112.561  , 235.979  ,  51.2664 , 112.607  , 224.858  ,  51.9736 ,
       112.959  , 212.587  ,  51.2097 , 113.022  , 204.526  ,  50.4888 ,
       112.627  , 192.513  ,  50.1693 , 112.808  , 183.724  ,  47.5524 ,
       112.288  , 171.345  ,  46.8534 , 112.233  , 162.69   ,  43.4192 ,
       111.337  , 152.24   ,  41.2016 , 111.453  , 142.327  ,  37.5963 ,
       110.868  , 134.702  ,  34.5887 , 110.022  , 123.729  ,  32.5556 ,
       109.63   , 115.57   ,  26.7696 , 108.584  , 104.427  ,  24.0688 ,
       107.945  ,  96.8253 ,  17.2024 , 106.826  ,  86.577  ,  14.6333 ,
       106.149  ,  78.465  ,   7.0065 , 104.992  ,  73.8841 ,   2.82648,
       103.663  ,  63.1727 ,   5.07401, 102.3    ,  59.0714 ,   9.60417,
       100.619  ,  50.7707 ,  14.7243 ,  99.314  , 

In [163]:
b = np.array([1,2,3,4,5,6,7,8,9,10])

In [164]:
step_in = 3
step_out = 3

c_in = np.zeros([len(b)+1-step_in-step_out, step_in])
c_out = np.zeros([len(b)+1-step_in-step_out, step_out])

for i in range(len(b)-step_in-step_out+1):
    c_in[i,:] = b[i:i+step_in]
    c_out[i,:] = b[i+step_in:i+step_in+step_out]

In [165]:
c_in

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.],
       [5., 6., 7.]])

In [166]:
c_out

array([[ 4.,  5.,  6.],
       [ 5.,  6.,  7.],
       [ 6.,  7.,  8.],
       [ 7.,  8.,  9.],
       [ 8.,  9., 10.]])

In [196]:
def split_seq(seq, step_x, step_y):
    tmp_x = np.zeros([len(seq)+1-step_x-step_y, step_x])
    tmp_y = np.zeros([len(seq)+1-step_x-step_y, step_y])
    
    for i in range(len(seq)-step_x-step_y+1):
        tmp_x[i, :] = seq[i:i+step_x]
        tmp_y[i, :] = seq[i+step_x:i+step_x+step_y]
    return tmp_x, tmp_y

In [197]:
def container(seq, step_x, step_y):
    tmp_x = np.zeros([len(seq)+1-step_x-step_y, step_x])
    tmp_y = np.zeros([len(seq)+1-step_x-step_y, step_y])
    return tmp_x, tmp_y

In [198]:
a

array([108.643  , 304.824  ,  42.4588 , 109.714  , 291.945  ,  45.2562 ,
       110.357  , 281.201  ,  47.1818 , 110.843  , 272.255  ,  48.5718 ,
       111.769  , 257.836  ,  50.0968 , 112.027  , 247.682  ,  50.9953 ,
       112.561  , 235.979  ,  51.2664 , 112.607  , 224.858  ,  51.9736 ,
       112.959  , 212.587  ,  51.2097 , 113.022  , 204.526  ,  50.4888 ,
       112.627  , 192.513  ,  50.1693 , 112.808  , 183.724  ,  47.5524 ,
       112.288  , 171.345  ,  46.8534 , 112.233  , 162.69   ,  43.4192 ,
       111.337  , 152.24   ,  41.2016 , 111.453  , 142.327  ,  37.5963 ,
       110.868  , 134.702  ,  34.5887 , 110.022  , 123.729  ,  32.5556 ,
       109.63   , 115.57   ,  26.7696 , 108.584  , 104.427  ,  24.0688 ,
       107.945  ,  96.8253 ,  17.2024 , 106.826  ,  86.577  ,  14.6333 ,
       106.149  ,  78.465  ,   7.0065 , 104.992  ,  73.8841 ,   2.82648,
       103.663  ,  63.1727 ,   5.07401, 102.3    ,  59.0714 ,   9.60417,
       100.619  ,  50.7707 ,  14.7243 ,  99.314  , 

In [199]:
#step_x = 15
#step_y = 9
d_in, d_out = container(a, 15, 9)
d_in, d_out = split_seq(a, 15, 9)
print(d_in)

[[108.643  304.824   42.4588 ... 111.769  257.836   50.0968]
 [304.824   42.4588 109.714  ... 257.836   50.0968 112.027 ]
 [ 42.4588 109.714  291.945  ...  50.0968 112.027  247.682 ]
 ...
 [-19.5861  35.2657  76.8567 ... -41.0983  30.9065  68.8301]
 [ 35.2657  76.8567 -26.8264 ...  30.9065  68.8301 -43.0721]
 [ 76.8567 -26.8264  36.1305 ...  68.8301 -43.0721  26.9277]]


In [200]:
print(d_out)

[[112.027  247.682   50.9953 ... 112.607  224.858   51.9736]
 [247.682   50.9953 112.561  ... 224.858   51.9736 112.959 ]
 [ 50.9953 112.561  235.979  ...  51.9736 112.959  212.587 ]
 ...
 [-43.0721  26.9277  67.8084 ...   0.       0.       0.    ]
 [ 26.9277  67.8084 -50.7076 ...   0.       0.       0.    ]
 [ 67.8084 -50.7076  25.3761 ...   0.       0.       0.    ]]


In [201]:
c1, c2 = container(b, 3, 2)
c1, c2 = split_seq(b , 3, 2)
c1

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.],
       [5., 6., 7.],
       [6., 7., 8.]])

In [235]:
def split_seq_2d(seq, step_x, step_y):
    tmp_x = np.zeros([seq.shape[0], seq.shape[1]+1-step_x-step_y, step_x])
    tmp_y = np.zeros([seq.shape[0], seq.shape[1]+1-step_x-step_y, step_y])
    for i in range(seq.shape[0]):
        for j in range(seq.shape[1]-step_x-step_y+1):
            tmp_x[i, j, :] = seq[i, j:j+step_x]
            tmp_y[i, j, :] = seq[i, j+step_x:j+step_x+step_y]
    
    #for i in range(len(seq)-step_x-step_y+1):
        #tmp_x[i, :] = seq[i:i+step_x]
        #tmp_y[i, :] = seq[i+step_x:i+step_x+step_y]
    return tmp_x, tmp_y

In [236]:
def container_2d(seq, step_x, step_y):
    tmp_x = np.zeros([seq.shape[0], seq.shape[1]+1-step_x-step_y, step_x])
    tmp_y = np.zeros([seq.shape[0], seq.shape[1]+1-step_x-step_y, step_y])
    return tmp_x, tmp_y

In [260]:
B = np.array([[1,2,3,4,5,6,7],[7,8,9,10,11,12,13]])
B.shape

(2, 7)

In [281]:
t1, t2 = container_2d(B, 3, 2)
#t1, t2 = split_seq_2d(B, 3, 2)
t1, t2 = split_seq_2d(B, 3, 2)

In [282]:
t1

array([[[ 1.,  2.,  3.],
        [ 2.,  3.,  4.],
        [ 3.,  4.,  5.]],

       [[ 7.,  8.,  9.],
        [ 8.,  9., 10.],
        [ 9., 10., 11.]]])

In [283]:
t2

array([[[ 4.,  5.],
        [ 5.,  6.],
        [ 6.,  7.]],

       [[10., 11.],
        [11., 12.],
        [12., 13.]]])

In [284]:
print(B.shape)
print(t1.shape)
print(t2.shape)

(2, 7)
(2, 3, 3)
(2, 3, 2)


In [255]:
A = traj[0:3, :]
A.shape

(3, 145)

In [285]:
t1, t2 = container_2d(A, 15, 9)
t1, t2 = split_seq_2d(A, 15, 9)

In [286]:
print(t1.shape)
print(t2.shape)

(3, 122, 15)
(3, 122, 9)


In [289]:
x_train, y_train = container_2d(traj, 15, 15)
x_train, y_train = split_seq_2d(traj, 15, 15)
print(traj.shape)
print(x_train.shape)
print(y_train.shape)

(3540, 145)
(3540, 116, 15)
(3540, 116, 15)


In [290]:
print(traj[1, :])

[  1.      108.919   301.744    43.7305  109.827   290.383    46.2671
 110.724   277.021    49.0714  111.334   267.009    50.5989  112.211
 252.849    52.5245  112.465   242.966    53.1224  112.493   231.433
  54.2488  113.122   219.631    54.3632  112.869   208.52     54.4683
 113.002   197.198    53.4586  112.605   185.618    53.2659  112.795
 175.557    50.9465  112.531   165.883    50.1104  111.674   156.011
  48.514   111.404   145.981    45.0985  110.497   134.487    43.5957
 110.204   126.021    39.2724  108.914   114.44     37.5008  108.188
 107.239    34.4154  107.364    99.6462   28.431   106.045    88.8893
  25.876   105.261    81.3033   19.0715  103.766    71.3441   16.0544
 102.774    64.1059    8.22109 101.678    56.8142    3.49632 100.131
  48.1284    3.94753  98.6115   44.4246    8.63298  96.9431   36.6074
  14.3458   95.2703   32.8375   18.3757   93.4944   25.0111   23.1444
  91.7746   21.7359   25.8056   90.374    17.4027   28.3971   88.0576
  11.334    31.7852   86.6

In [291]:
print(x_train[1, :, :])

[[  1.     108.919  301.744  ...  50.5989 112.211  252.849 ]
 [108.919  301.744   43.7305 ... 112.211  252.849   52.5245]
 [301.744   43.7305 109.827  ... 252.849   52.5245 112.465 ]
 ...
 [-14.0566  39.1442  77.5297 ... -34.4775  39.9743  69.6342]
 [ 39.1442  77.5297 -17.8248 ...  39.9743  69.6342 -37.0719]
 [ 77.5297 -17.8248  39.4014 ...  69.6342 -37.0719  36.7475]]


In [292]:
dataset = pd.read_csv('./datasets/dataset_20200225_for_prediction.csv')
dataset = dataset.fillna(0)

In [293]:
dataset = np.array(dataset)

In [294]:
x_train, y_train = container_2d(dataset, 15, 15)
x_train, y_train = split_seq_2d(dataset, 15, 15)
print(dataset.shape)
print(x_train.shape)
print(y_train.shape)

(3540, 144)
(3540, 115, 15)
(3540, 115, 15)


In [298]:
print(dataset[0, :])

[108.643   304.824    42.4588  109.714   291.945    45.2562  110.357
 281.201    47.1818  110.843   272.255    48.5718  111.769   257.836
  50.0968  112.027   247.682    50.9953  112.561   235.979    51.2664
 112.607   224.858    51.9736  112.959   212.587    51.2097  113.022
 204.526    50.4888  112.627   192.513    50.1693  112.808   183.724
  47.5524  112.288   171.345    46.8534  112.233   162.69     43.4192
 111.337   152.24     41.2016  111.453   142.327    37.5963  110.868
 134.702    34.5887  110.022   123.729    32.5556  109.63    115.57
  26.7696  108.584   104.427    24.0688  107.945    96.8253   17.2024
 106.826    86.577    14.6333  106.149    78.465     7.0065  104.992
  73.8841    2.82648 103.663    63.1727    5.07401 102.3      59.0714
   9.60417 100.619    50.7707   14.7243   99.314    46.2701   18.3093
  97.7961   41.8541   21.4989   96.0541   33.8609   25.6685   94.4366
  29.7369   27.9363   92.7192   21.8017   31.4817   90.9287   18.1181
  32.4892   89.2632   10.186

In [295]:
print(x_train[0, :, :])

[[108.643   304.824    42.4588  ... 111.769   257.836    50.0968 ]
 [304.824    42.4588  109.714   ... 257.836    50.0968  112.027  ]
 [ 42.4588  109.714   291.945   ...  50.0968  112.027   247.682  ]
 ...
 [ -9.07679  36.406    80.5685  ... -29.9512   32.5259   72.9632 ]
 [ 36.406    80.5685  -16.0423  ...  32.5259   72.9632  -36.8209 ]
 [ 80.5685  -16.0423   37.803   ...  72.9632  -36.8209   32.4545 ]]


In [296]:
print(y_train[0, :, :])

[[112.027  247.682   50.9953 ... 113.022  204.526   50.4888]
 [247.682   50.9953 112.561  ... 204.526   50.4888 112.627 ]
 [ 50.9953 112.561  235.979  ...  50.4888 112.627  192.513 ]
 ...
 [-36.8209  32.4545  71.5898 ...   0.       0.       0.    ]
 [ 32.4545  71.5898 -41.0983 ...   0.       0.       0.    ]
 [ 71.5898 -41.0983  30.9065 ...   0.       0.       0.    ]]
