In [1]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, TimeDistributed
from keras.utils import to_categorical
import numpy as np

Using TensorFlow backend.
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lab606a/.virtualenvs/keras/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lab606a/.virtualenvs

In [2]:
model = Sequential()
model.add(LSTM(32, return_sequences=True, input_shape=(None, 5)))
model.add(LSTM(8, return_sequences=True))
model.add(TimeDistributed(Dense(2, activation='sigmoid')))

In [3]:
print(model.summary(90))

__________________________________________________________________________________________
Layer (type)                            Output Shape                        Param #       
lstm_1 (LSTM)                           (None, None, 32)                    4864          
__________________________________________________________________________________________
lstm_2 (LSTM)                           (None, None, 8)                     1312          
__________________________________________________________________________________________
time_distributed_1 (TimeDistributed)    (None, None, 2)                     18            
Total params: 6,194
Trainable params: 6,194
Non-trainable params: 0
__________________________________________________________________________________________
None


In [4]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, None, 32)          4864      
_________________________________________________________________
lstm_2 (LSTM)                (None, None, 8)           1312      
_________________________________________________________________
time_distributed_1 (TimeDist (None, None, 2)           18        
Total params: 6,194
Trainable params: 6,194
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.compile(loss='categorical_crossentropy', optimizer='adam')

In [15]:
def train_generator():
    while True:
        sequence_length = np.random.randint(10, 100)
        x_train = np.random.random((1000, sequence_length, 5))
        # y_train will depend on past 5 timesteps of x
        y_train = x_train[:, :, 0]
        for i in range(1, 5):
            y_train[:, i:] += x_train[:, :-i, i]
        y_train = to_categorical(y_train > 2.5)
        print("\nshape of x_train = ", x_train.shape)
        print("shape of y_train = ", y_train.shape)
        yield x_train, y_train

In [17]:
model.fit_generator(train_generator(), steps_per_epoch=30, epochs=10, verbose=1)

Epoch 1/10

shape of x_train =  (1000, 69, 5)
shape of y_train =  (1000, 69, 2)

shape of x_train =  (1000, 71, 5)
shape of y_train =  (1000, 71, 2)

shape of x_train =  (1000, 22, 5)
shape of y_train =  (1000, 22, 2)

shape of x_train =  (1000, 21, 5)
shape of y_train =  (1000, 21, 2)

shape of x_train =  (1000, 45, 5)
shape of y_train =  (1000, 45, 2)

shape of x_train =  (1000, 43, 5)
shape of y_train =  (1000, 43, 2)

shape of x_train =  (1000, 69, 5)
shape of y_train =  (1000, 69, 2)

shape of x_train =  (1000, 40, 5)
shape of y_train =  (1000, 40, 2)

shape of x_train =  (1000, 99, 5)
shape of y_train =  (1000, 99, 2)

shape of x_train =  (1000, 30, 5)
shape of y_train =  (1000, 30, 2)

shape of x_train =  (1000, 23, 5)
shape of y_train =  (1000, 23, 2)

shape of x_train =  (1000, 66, 5)
shape of y_train =  (1000, 66, 2)
 1/30 [>.............................] - ETA: 3s - loss: 0.0215
shape of x_train =  (1000, 24, 5)
shape of y_train =  (1000, 24, 2)
 2/30 [=>....................

 4/30 [===>..........................] - ETA: 2s - loss: 0.0194
shape of x_train =  (1000, 80, 5)
shape of y_train =  (1000, 80, 2)
 5/30 [====>.........................] - ETA: 2s - loss: 0.0195
shape of x_train =  (1000, 58, 5)
shape of y_train =  (1000, 58, 2)
 6/30 [=====>........................] - ETA: 2s - loss: 0.0195
shape of x_train =  (1000, 81, 5)
shape of y_train =  (1000, 81, 2)
 7/30 [======>.......................] - ETA: 2s - loss: 0.0195
shape of x_train =  (1000, 76, 5)
shape of y_train =  (1000, 76, 2)

shape of x_train =  (1000, 52, 5)
shape of y_train =  (1000, 52, 2)
 9/30 [========>.....................] - ETA: 1s - loss: 0.0190
shape of x_train =  (1000, 50, 5)
shape of y_train =  (1000, 50, 2)
10/30 [=========>....................] - ETA: 1s - loss: 0.0191
shape of x_train =  (1000, 46, 5)
shape of y_train =  (1000, 46, 2)
11/30 [==========>...................] - ETA: 1s - loss: 0.0192
shape of x_train =  (1000, 80, 5)
shape of y_train =  (1000, 80, 2)
12/30 [

10/30 [=========>....................] - ETA: 1s - loss: 0.0185
shape of x_train =  (1000, 97, 5)
shape of y_train =  (1000, 97, 2)
11/30 [==========>...................] - ETA: 1s - loss: 0.0185
shape of x_train =  (1000, 26, 5)
shape of y_train =  (1000, 26, 2)
12/30 [===========>..................] - ETA: 1s - loss: 0.0184
shape of x_train =  (1000, 56, 5)
shape of y_train =  (1000, 56, 2)
13/30 [============>.................] - ETA: 1s - loss: 0.0185
shape of x_train =  (1000, 87, 5)
shape of y_train =  (1000, 87, 2)
14/30 [=============>................] - ETA: 1s - loss: 0.0184
shape of x_train =  (1000, 11, 5)
shape of y_train =  (1000, 11, 2)
15/30 [==============>...............] - ETA: 1s - loss: 0.0184
shape of x_train =  (1000, 42, 5)
shape of y_train =  (1000, 42, 2)
16/30 [===============>..............] - ETA: 1s - loss: 0.0184
shape of x_train =  (1000, 52, 5)
shape of y_train =  (1000, 52, 2)

shape of x_train =  (1000, 73, 5)
shape of y_train =  (1000, 73, 2)
18/30 [

17/30 [================>.............] - ETA: 1s - loss: 0.0176
shape of x_train =  (1000, 40, 5)
shape of y_train =  (1000, 40, 2)
18/30 [=================>............] - ETA: 1s - loss: 0.0176
shape of x_train =  (1000, 17, 5)
shape of y_train =  (1000, 17, 2)

shape of x_train =  (1000, 58, 5)
shape of y_train =  (1000, 58, 2)
20/30 [===================>..........] - ETA: 0s - loss: 0.0175
shape of x_train =  (1000, 27, 5)
shape of y_train =  (1000, 27, 2)
21/30 [====================>.........] - ETA: 0s - loss: 0.0176
shape of x_train =  (1000, 94, 5)
shape of y_train =  (1000, 94, 2)
22/30 [=====================>........] - ETA: 0s - loss: 0.0176
shape of x_train =  (1000, 73, 5)
shape of y_train =  (1000, 73, 2)
23/30 [======================>.......] - ETA: 0s - loss: 0.0176
shape of x_train =  (1000, 94, 5)
shape of y_train =  (1000, 94, 2)
24/30 [=======================>......] - ETA: 0s - loss: 0.0176
shape of x_train =  (1000, 61, 5)
shape of y_train =  (1000, 61, 2)
25/30 [

24/30 [=======================>......] - ETA: 0s - loss: 0.0174
shape of x_train =  (1000, 14, 5)
shape of y_train =  (1000, 14, 2)

shape of x_train =  (1000, 79, 5)
shape of y_train =  (1000, 79, 2)
26/30 [=========================>....] - ETA: 0s - loss: 0.0173
shape of x_train =  (1000, 18, 5)
shape of y_train =  (1000, 18, 2)
27/30 [==========================>...] - ETA: 0s - loss: 0.0173
shape of x_train =  (1000, 96, 5)
shape of y_train =  (1000, 96, 2)
28/30 [===========================>..] - ETA: 0s - loss: 0.0173
shape of x_train =  (1000, 45, 5)
shape of y_train =  (1000, 45, 2)
29/30 [============================>.] - ETA: 0s - loss: 0.0173
shape of x_train =  (1000, 83, 5)
shape of y_train =  (1000, 83, 2)
30/30 [==============================] - 3s 91ms/step - loss: 0.0173
Epoch 10/10

shape of x_train =  (1000, 42, 5)
shape of y_train =  (1000, 42, 2)
 1/30 [>.............................] - ETA: 2s - loss: 0.0171
shape of x_train =  (1000, 92, 5)
shape of y_train =  (10

In [18]:
seq_len = np.random.randint(10,100)
print(seq_len)

41


In [19]:
x_train = np.random.random((1000, seq_len, 5))
print(x_train)

[[[1.01874905e-02 3.26415903e-01 5.15248450e-01 1.61727431e-01
   4.96845433e-01]
  [8.66837759e-01 2.84310657e-01 9.85998127e-01 2.21929076e-02
   2.93432137e-01]
  [4.89139438e-01 3.12828507e-01 5.90975145e-01 9.69164993e-01
   2.90230742e-02]
  ...
  [2.56408545e-01 5.16491173e-01 1.11393353e-01 3.02091191e-01
   4.49571887e-01]
  [4.60253938e-01 6.03558244e-01 3.87413923e-01 5.52600980e-01
   4.67237768e-01]
  [7.15433637e-01 5.17317887e-01 1.33598917e-01 6.14023166e-01
   5.34459653e-01]]

 [[2.93580515e-01 5.54655603e-01 3.74158352e-01 7.50855789e-01
   2.32215060e-01]
  [6.98384983e-01 9.49615551e-01 7.35925733e-01 1.55120655e-01
   7.49700476e-01]
  [7.83938111e-01 1.34510508e-01 3.23866592e-01 5.66467857e-01
   3.47000287e-03]
  ...
  [3.43496140e-01 5.76633595e-02 7.51692487e-01 6.11787724e-01
   3.05378792e-01]
  [8.37072320e-01 8.58830430e-02 8.89969365e-01 1.15282446e-01
   3.58506623e-01]
  [6.62688002e-01 1.76372785e-03 9.71577495e-01 6.40354143e-01
   2.97425489e-01]]



In [20]:
print(x_train.shape)
print(x_train[0].shape)

(1000, 41, 5)
(41, 5)


In [21]:
y_train = x_train[:, :, 0]
print(y_train)

[[1.01874905e-02 8.66837759e-01 4.89139438e-01 ... 2.56408545e-01
  4.60253938e-01 7.15433637e-01]
 [2.93580515e-01 6.98384983e-01 7.83938111e-01 ... 3.43496140e-01
  8.37072320e-01 6.62688002e-01]
 [6.80067439e-01 8.77794809e-01 8.12939270e-01 ... 7.77682199e-04
  7.21357122e-01 6.48073453e-01]
 ...
 [5.46823422e-01 3.07599239e-01 7.86795885e-01 ... 6.17859748e-01
  1.15986724e-01 6.92950021e-01]
 [5.01712577e-01 7.29456588e-01 2.25700817e-01 ... 4.17665739e-01
  4.98611583e-01 6.15970111e-01]
 [8.45885509e-01 5.78928163e-01 2.97197393e-01 ... 4.76088721e-01
  2.59925492e-01 1.34458973e-01]]


In [22]:
print(y_train.shape)
print(y_train[0].shape)

(1000, 41)
(41,)


In [23]:
for i in range(1, 5):
    y_train[:,i:] += x_train[:, :-i, i]
print(y_train)
print(y_train.shape)

[[0.01018749 1.19325366 1.28869854 ... 1.60139449 2.81296638 2.73849285]
 [0.29358052 1.25304059 2.10771201 ... 2.80322136 1.98791703 2.02722298]
 [0.68006744 0.99947748 2.20799046 ... 1.7820567  1.98568705 2.34452482]
 ...
 [0.54682342 0.96485303 2.29159546 ... 2.64702351 1.43805454 3.73891441]
 [0.50171258 1.2246193  0.6303629  ... 1.44399832 3.05056497 2.74741397]
 [0.84588551 1.14220144 1.85035725 ... 3.32897251 1.77557216 2.799709  ]]
(1000, 41)


In [24]:
y_train = to_categorical(y_train > 2.5)
#print(y_train)
print(x_train.shape)
print(y_train.shape)

(1000, 41, 5)
(1000, 41, 2)
